"""Build reports/2026-09-23-ns3d-shift-head.md from the pulled run JSONs. No hand-typed numbers.

Usage: /home/tahmid/Dev/.venv/bin/python reports/build_2026-09-23-ns3d-shift-head.py
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LANE = ROOT / "experiments" / "ns3d-shift-head"
sys.path.insert(0, str(LANE))
import write_tables as W  # noqa: E402

DEV_JOBS = ["a2_h32", "a2_h64", "a3_h96"]
HELDOUT_JOB = "b2_heldout96"
CRASHED = "b1_heldout96_crashed"
V1_JOBS = ["a1_h32", "a1_h64"]


def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def pct(x, nd=3):
    return W.pct(x, nd)


def ladder_rows(s):
    cfg = s["config"]
    rows = [r for r in W.rom_rows(s) if r["dt"] == cfg["ladder_dt"]
            and r["iters"] == cfg["ladder_iters"]]
    span = sorted([r for r in rows if r["kind"] == "span"], key=lambda r: -r["rank"])
    head = [r for r in rows if r["kind"] == "head" and r["k"] == s["k_selected"]][0]
    return span, head


def speed(s, row, fam, heavy=False):
    c = W.comparator(W.fom_rows(s), fam, row["worst"])
    if c is None:
        return None, None
    t = row["ms_heavy"] if heavy and row.get("ms_heavy") else row["ms"]
    return c, c["ms"] / t


def main():
    have = [j for j in DEV_JOBS if (LANE / "runs" / j / "output" / "summary.json").exists()]
    S = {j: W.load(j)[0] for j in have}
    V = {j: W.load(j)[1] for j in have}
    L = []
    L.append("# NS3D: the paper's head and the importance-ordered bank inside the co-moving frame\n")
    held = (LANE / "runs" / HELDOUT_JOB / "output" / "summary.json")
    status = ("Development numbers are final for meshes " +
              ", ".join(f"{S[j]['config']['n']}^3" for j in have) + ". " +
              ("The held-out seed was opened once; its section is below."
               if held.exists() else "The held-out seed has **not** been opened."))
    L.append("Lane `exp/2026-09-23-ns3d-shift-head` (forked from the co-moving-frame lane "
             "`exp/2026-09-22-ns3d-shift-decoder`). It runs the paper's nonlinear head inside the "
             "parent's co-moving frame, and the paper's importance-ordered bank span as the "
             "tunability ladder, on 3D periodic Navier–Stokes at three meshes, each paired with a "
             "spectral FOM (CNAB2) and an iterative finite-difference FOM (FD-CG) in the same "
             f"allocation. {status} Generated by `reports/build_2026-09-23-ns3d-shift-head.py`.\n")

    L.append("## What was run\n")
    L.append(r"""The parent lane writes the state as $u(x,t)=v(x-c(t),t)$ with $v$ in a fixed centered rank-64 POD bank $G$, and solves the frame increment $\delta=c^{n+1}-c^n$ online from the same weak residual; all reduced tensors are offline. This lane keeps that bank and frame and changes only the trial set of $v$. After a direction change from the user (correction directions removed from the paper), the two arms are:

- **(a) head only:** $v=G\,h_\theta(z)$, unknowns $(z,\delta)\in\mathbb R^{k+3}$. $h_\theta$ is the paper's head (two hidden SiLU layers of width 256 plus a linear skip), trained as an auto-decoder on the centred bank coefficients of training-seed states only. $k\in\{8,16,32\}$; $k$ is selected on development by a rule fixed in advance.
- **(b) bank span:** the bank is rotated once offline to importance order, $G_r=GV$ with $V$ the eigenvectors of the training coefficients' second moment $\Sigma$ (equivalently the SVD of $G\Sigma^{1/2}$), and $v=G_r[:, :R']\,c$ with unknowns $(c,\delta)\in\mathbb R^{R'+3}$, $R'\in\{64,48,32,16,8\}$. $R'$ is the tunability knob; $R'=64$ is the parent's linear arm in rotated coordinates.

Both are solved with the parent's fixed-sweep damped Gauss–Newton (analytic Jacobian, Cholesky); the head's Jacobian is the parent's coefficient Jacobian chained with $\partial h/\partial z$.

```mermaid
flowchart LR
  U0["u0"] --> C0["centre on energy centroid"]
  C0 --> P["project on G"]
  P --> ENC["nearest code + GN encoder (head)<br/>or truncate to R' (span)"]
  ENC --> STEP["per step: damped GN on (z or c, delta)<br/>stored A, T, D_d"]
  STEP --> STEP
  STEP --> OUT["shift(G a, c) at output times"]
  classDef frozen fill:#e8eef7,stroke:#41618f,color:#12243d;
  classDef solved fill:#fdf0e2,stroke:#b5762a,color:#4a2f0c;
  classDef grid fill:#eaf3ea,stroke:#4a7a4a,color:#1d3b1d;
  class P,ENC frozen;
  class STEP solved;
  class C0,OUT grid;
```
""")

    L.append(W.headline(have))

    if have:
        L.append("## Findings\n")
        for j in have:
            s = S[j]
            n = s["config"]["n"]
            span, head = ladder_rows(s)
            top, bottom = span[0], span[-1]
            cA, xA = speed(s, head, "CNAB2")
            cT, xT = speed(s, top, "CNAB2")
            cB, xB = speed(s, bottom, "CNAB2")
            err_mono = all(a["worst"] <= b["worst"] for a, b in zip(span, span[1:]))
            cost_mono = all(a["ms"] >= b["ms"] for a, b in zip(span, span[1:]))
            fl = s["head_floors"][str(s["k_selected"])]["0"]["evolved_worst"]
            text = (f"**{n}^3 (job {s['job_id']}).** The selected head (k={s['k_selected']}) "
                    f"reaches {pct(head['worst'])} evolved worst against a head floor of "
                    f"{pct(fl)}, at {W.ms(head['ms'])} ms "
                    f"({'—' if xA is None else f'{xA:.2f}x'} CNAB2). The span ladder runs from "
                    f"R'={top['rank']} at {pct(top['worst'])} / {W.ms(top['ms'])} ms "
                    f"({'—' if xT is None else f'{xT:.2f}x'}) to R'={bottom['rank']} at "
                    f"{pct(bottom['worst'])} / {W.ms(bottom['ms'])} ms "
                    f"({'—' if xB is None else f'{xB:.2f}x'}). Monotone in error: **{err_mono}**; "
                    f"in cost: **{cost_mono}**.")
            same = [r for r in span if r["rank"] == s["k_selected"]]
            if same:
                text += (f" At equal size (R'=k={s['k_selected']}) the span's error is "
                         f"{same[0]['worst'] / head['worst']:.0f}x the head's, and the head costs "
                         f"{head['ms'] / same[0]['ms']:.2f}x the span's time.")
            L.append(text)
            L.append("")
        L.append(r"""**Why the head is so much more accurate than the full span.** The span's error at $R'=64$ is several times its own representation floor; the gap is reduced-dynamics error in 64 linear directions (the parent lane saw the same). The head's trial set is a $k$-dimensional manifold fitted to true centred states, so the Gauss–Newton solve can only return states near that manifold, and its solved error sits close to its floor. The family is low-dimensional once translation is factored out (separation, strength, viscosity and time), which is why $k=8$ is enough and larger $k$ does not help. This is a development finding on one parametric family; it says the head removes the spurious reduced dynamics, not that it generalises beyond the family it was trained on.

**What the head costs.** It is the most expensive reduced arm per query: its unknown count is small, but each sweep evaluates the network and its Jacobian and chains it through the $M\times R$ coefficient Jacobian, and the query is launch-bound, so fewer unknowns do not buy time. The span ladder is the cost knob; the head is the accuracy end.
""")

    # success criteria, generated
    L.append("## Against the lane's success criteria\n")
    L.append("| cohort | mesh | ladder monotone in error | in cost | accurate end (worst) | "
             "≲1 %? | fast end (worst, vs CNAB2) | faster than CNAB2? | faster than FD-CG? |")
    L.append("|---|---:|---|---|---|---|---|---|---|")
    cohorts = [(j, S[j], "development") for j in have]
    if held.exists():
        cohorts.append((HELDOUT_JOB, W.load(HELDOUT_JOB)[0], "held-out"))
    for j, s, label in cohorts:
        span, head = ladder_rows(s)
        em = all(a["worst"] <= b["worst"] for a, b in zip(span, span[1:]))
        cm = all(a["ms"] >= b["ms"] for a, b in zip(span, span[1:]))
        acc = min([head] + span, key=lambda r: r["worst"])
        fast = min(span, key=lambda r: r["ms"])
        _, xc = speed(s, fast, "CNAB2")
        cf, xf = speed(s, fast, "FD-CG", heavy=True)
        L.append(f"| {label} | {s['config']['n']}^3 | {em} | {cm} | {acc['label']} "
                 f"{pct(acc['worst'])} | {acc['worst'] <= 0.01} | {fast['label']} "
                 f"{pct(fast['worst'])}, {'—' if xc is None else f'{xc:.2f}x'} | "
                 f"{xc is not None and xc > 1} | "
                 f"{'no comparator' if xf is None else f'{xf > 1} ({xf:.2f}x conservative)'} |")
    L.append("")

    # FOM finding
    L.append("## The FOM solvers\n")
    L.append(r"""**CNAB2 is spectral and performs no linear solve.** `experiments/ns3d/ns3d_fom.py:make_solver` is a Fourier pseudo-spectral Galerkin method with 2/3 dealiasing: the Crank–Nicolson viscous step is a pointwise division by $1+\tfrac12\Delta t\,\nu|k|^2$ in Fourier space, and the pressure is removed by the Leray projector $\hat u-k(k\cdot\hat u)/|k|^2$, also pointwise. Every "solve" is an FFT pair. Under the project's rule against featuring spectral/direct solvers as the comparator, it is not a rule-compliant FOM.

**FD-CG (added here) is.** `experiments/ns3d-shift-head/fd_fom.py`: second-order central differences on the same periodic grid, rotational advection with AB2, Crank–Nicolson viscous step solved by conjugate gradients, and an exact discrete projection whose central-difference Poisson problem is solved by (warm-started) conjugate gradients. It is tested at the job's mesh over steps × CG tolerances and on finer meshes ($2n$, and $3n$ at $96^3$) injected onto the coarse grid. Its error against the spectral truth is dominated by its own second-order spatial error, so matching the head's accuracy needs a much finer grid, and unpreconditioned CG on the pressure Poisson problem costs tens to hundreds of iterations per step. FD-CG speedups are therefore large and should be read as "against a plain iterative solver", not as a statement about an efficient FOM; the CNAB2 column is the honest efficiency comparison.
""")
    L.append("| mesh | cheapest FD-CG setting within 5 % | its worst | ms | most accurate FD-CG | its worst | ms | CNAB2 at similar or better accuracy | ms |")
    L.append("|---:|---|---:|---:|---|---:|---:|---|---:|")
    for j in have:
        s = S[j]
        foms = W.fom_rows(s)
        fd = [f for f in foms if f["family"] == "FD-CG" and f["stable"] and f["worst"] is not None]
        ok = [f for f in fd if f["worst"] <= 0.05]
        cheap = min(ok, key=lambda f: f["ms"]) if ok else None
        best = min(fd, key=lambda f: f["worst"])
        cn = W.comparator(foms, "CNAB2", best["worst"])
        L.append(f"| {s['config']['n']}^3 | {cheap['label'] if cheap else '—'} | "
                 f"{pct(cheap['worst']) if cheap else '—'} | {W.ms(cheap['ms']) if cheap else '—'} | "
                 f"{best['label']} | {pct(best['worst'])} | {W.ms(best['ms'])} | "
                 f"{cn['label'] if cn else '—'} | {W.ms(cn['ms']) if cn else '—'} |")
    L.append("")

    # held-out
    L.append("## Held-out evaluation\n")
    if held.exists():
        hs = json.loads(held.read_text())
        hv = W.load(HELDOUT_JOB)[1]
        L.append(f"Opened once: job {hs['job_id']}, seed {hs['config']['dev_seed']}, "
                 f"{hs['config']['dev_cases']} cases, mesh {hs['config']['n']}^3, frozen settings "
                 f"sha256 `{hs['frozen_settings_sha256']}`, head checkpoint sha256 "
                 f"`{hs['frozen_head_sha256']}`, bank rebuild gap {hs['bank_rebuild_gap']:.1e}, "
                 f"disjointness {hs['heldout_disjointness']}.\n")
        L.append(W.headline([HELDOUT_JOB]).split("\n", 2)[2]
                 .replace("development evolved worst", "held-out evolved worst"))
        cp = LANE / "runs" / CRASHED / "output" / "summary.json"
        if cp.exists():
            cs = json.loads(cp.read_text())
            gaps, n_rows, gfd, n_fd = 0.0, 0, 0.0, 0
            for sec in ("linear", "span", "frontier", "cnab2", "fd_cg"):
                for key, e in cs.get(sec, {}).items():
                    f = hs.get(sec, {}).get(key)
                    if f and e.get("errors") is not None and f.get("errors") is not None:
                        a, b = e["errors"], f["errors"]
                        d = max(abs(x - y) / max(1.0, abs(y)) for ra, rb in zip(a, b)
                                for x, y in zip(ra, rb))
                        if sec == "fd_cg":
                            gfd, n_fd = max(gfd, d), n_fd + 1
                        else:
                            gaps, n_rows = max(gaps, d), n_rows + 1
            L.append(f"\nThe held-out seed was opened by job {cs['job_id']}, which crashed in "
                     "its audit of a blown-up FD-CG row before timing (DESIGN amendment 4; "
                     f"record at `runs/{CRASHED}/`). This rerun, job {hs['job_id']}, uses the "
                     f"same frozen settings. Over the {n_rows} reduced-model and CNAB2 rows both runs "
                     f"computed, the largest per-case error difference is {gaps:.1e}; over the "
                     f"{n_fd} FD-CG rows it is {gfd:.1e} (CG reductions are not bitwise "
                     "reproducible on the GPU; relative to max(1, error)).\n")
        sp, hd = ladder_rows(hs)
        dv = S.get("a3_h96")
        if dv:
            dsp, dhd = ladder_rows(dv)
            L.append("| arm | development worst | held-out worst | held-out median | held-out over 5 % |")
            L.append("|---|---:|---:|---:|---:|")
            for a, b in zip([dhd] + dsp, [hd] + sp):
                L.append(f"| {b['label']} | {pct(a['worst'])} | {pct(b['worst'])} | "
                         f"{pct(b['median'])} | {b['over']}/{b['cases']} |")
            L.append("")
    else:
        L.append("Not opened.\n")

    # gates / retractions
    L.append("## Gates, controls and what went wrong\n")
    gate_jobs = [(j, S[j], V[j]) for j in have]
    if held.exists():
        gate_jobs.append((HELDOUT_JOB,) + tuple(W.load(HELDOUT_JOB)[:2]))
    for j, s, v in gate_jobs:
        t = s["timing"]
        fz = s["control_frame_zero"]["stats"]
        L.append(f"- **{s['config']['n']}^3{' held-out' if s.get('heldout_opened') else ''}:** frozen-frame control {pct(fz['evolved_worst'])} "
                 f"({fz['cases_evolved_over_target']}/{fz['cases']} over 5 %, must fail); head driver "
                 f"parity vs generic LM at 3 sweeps {s['head_parity_vs_lm']['parity']['3']:.1e}; "
                 f"rotation gate {s['rotation']['rotated_vs_rebuilt_operators']:.1e}; timing gates "
                 f"fast-block {t['neighbour_gate_fast_block_passed']}, after-cool-down "
                 f"{t['neighbour_gate_after_cooldown_passed']}; NumPy audit gap "
                 f"{v['worst_gap_float64']:.1e} (control rejected: {v['control_rejected']}); "
                 f"timed-output agreement {t['timed_output_error_agreement']:.1e}.")
    L.append("""- **Retracted: the v1 FD-CG timings.** `a1_h64` (job 4197294) failed the pre-registered neighbour gate: ladder arms were 17–23 % slower when timed right after the seconds-long FD-CG arm at $128^3$, while staying within 2.3 % inside the randomised fast block. Its accuracy stands (reproduced exactly by `a2_h64`); its FD-CG ratios do not. Timing v2 (DESIGN amendment 2) was introduced and every mesh rerun; the 96^3 v1 job was cancelled before timing. `a1_h32` passed the v1 gate and is kept only as a record.
- **The held-out job ran twice.** The first held-out job crashed in its own audit (an absolute float32 bound tripped by a blown-up FD-CG row) after computing every reduced-model and CNAB2 row but before timing; the audit tolerance was made relative and the identical frozen settings rerun (DESIGN amendment 4). Nothing was selected between the two runs; the reproducibility check is in the held-out section.
- **Design changed mid-lane, before any job:** the correction directions $C_q$ were dropped at the user's direction and replaced by the importance-ordered span ladder (DESIGN amendment 1).
- **Comparator granularity.** The CNAB2 grid has no step between 40 and 50 steps at the finer meshes, and FD-CG accuracy jumps between meshes, so a comparator can be much more accurate (and slower) than the arm it is matched to; comparators, their errors and times are printed beside every ratio.
""")
    L.append("## Provenance\n")
    L.append("| job | mesh | slurm id | GPU | commit | summary.json | sha256 |")
    L.append("|---|---:|---:|---|---|---|---|")
    for j in have + ([HELDOUT_JOB] if held.exists() else []):
        s = S.get(j) or json.loads(held.read_text())
        p = LANE / "runs" / j / "output" / "summary.json"
        L.append(f"| {j} | {s['config']['n']}^3 | {s['job_id']} | {s['gpu'].split(',')[0]} | "
                 f"`{s['source_commit'][:10]}` | `{p.relative_to(ROOT)}` | `{sha(p)}` |")
    L.append("\nPer-mesh detail (floors, full frontier, FOM grids, head training, gates): "
             "`experiments/ns3d-shift-head/results/<job>.md`.\n")
    L.append("""## Glossary

- **bank $G$** — fixed spatial basis (centred POD, rank 64) the reduced state lives in.
- **importance order / $G_r$, $R'$** — the bank rotated so its columns are ordered by training energy; $R'$ is how many leading columns are used.
- **head $h_\\theta$, $k$** — small network mapping a $k$-number code to bank coefficients.
- **co-moving frame, $\\delta$** — the vortex's translation, solved each step alongside the coefficients.
- **floor** — error of the best reconstruction a trial set allows, with the true frame, before any time stepping.
- **evolved worst / median** — per case, worst relative $L^2$ error over output times after $t=0$ (relative to $\\lVert u_0\\rVert$); then the worst / median over cases.
- **over 5 %** — number of cases whose evolved worst exceeds 5 %.
- **GPU ms** — median wall time of one complete query (initial centring, solve, all output fields) in the job's randomised interleaved timing block.
- **after heavy** — the same arm timed immediately after the heaviest FD-CG run; the conservative time for FD-CG ratios.
- **CNAB2** — the spectral FOM (Crank–Nicolson viscous, Adams–Bashforth-2 advection); no linear solve.
- **FD-CG** — the finite-difference FOM whose viscous and pressure systems are solved by conjugate gradients.
- **comparator** — the fastest stable FOM setting (of one family) at least as accurate as the arm; speedup = its time / the arm's time, same job.
- **sweeps** — fixed Gauss–Newton iterations per time step.
- **development / held-out** — cases used to choose settings / never-seen cases evaluated once with frozen settings.
""")
    out = ROOT / "reports" / "2026-09-23-ns3d-shift-head.md"
    out.write_text("\n".join(L))
    print("wrote", out)


if __name__ == "__main__":
    main()
