"""Build reports/2026-10-01-ns3d-coordnet-bank.md from the pulled run JSONs of the
ns3d-coordnet lane. No number in the report is typed by hand: every number is read from a
run summary, an audit file or a results JSON listed in the provenance table.

Usage: /home/tahmid/Dev/.venv/bin/python reports/build_2026-10-01-ns3d-coordnet-bank.py
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LANE = ROOT / "experiments" / "ns3d-coordnet"
RUNS = LANE / "runs"
MESHES = ("32", "64", "96")
K = 8


def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def load(path):
    p = Path(path)
    return json.loads(p.read_text()) if p.exists() else None


def pct(x, nd=3):
    return "—" if x is None else f"{100 * x:.{nd}f}%"


def num(x, fmt=".2e"):
    return "—" if x is None else format(x, fmt)


def rx(x, nd=2):
    return "—" if x is None else f"{x:.{nd}f}x"


def yes(b):
    return "**PASS**" if b else "**FAIL**"


def main():
    plan = load(LANE / "results" / "report_plan.json")
    pilot = load(RUNS / "pilot" / "output" / "summary.json")
    ff = load(RUNS / plan["fixed_frame_run"] / "output" / "summary.json")
    samp = load(LANE / "results" / "pilot_bank_meshes.json")
    samp2 = load(LANE / "results" / "pilot_bank_meshes_64_96.json")
    lfc = load(LANE / "results" / "local_floor_check_pilot.json")
    dev = {m: load(RUNS / plan["dev"][m] / "output" / "mesh" / "summary.json") for m in MESHES}
    devv = {m: load(RUNS / plan["dev"][m] / "output" / "mesh" / "verify.json") for m in MESHES}
    dev = {m: s for m, s in dev.items() if s}
    test, testv = {}, {}
    if plan.get("test"):
        for m in MESHES:
            s = load(RUNS / plan["test"] / "output" / f"test{m}" / "summary.json")
            if s:
                test[m] = s
                testv[m] = load(RUNS / plan["test"] / "output" / f"test{m}" / "verify.json")
    frozen = load(LANE / "frozen" / "frozen_settings.json")
    hk = f"coordnet_head_k{K}"
    L = []
    w = L.append

    # ---------------------------------------------------------------- header --
    w("# NS3D: one coordinate-network bank inside the co-moving frame\n")
    w("Lane `exp/2026-10-01-ns3d-coordnet-bank` tests whether **one** trained coordinate-network bank, "
      "sampled unchanged at $32^3$, $64^3$ and $96^3$, can replace the paper's per-mesh rank-64 centred POD "
      "bank inside the same co-moving frame, with the same $k=8$ head recipe and solver. "
      f"Status: development numbers are final for {', '.join(f'{m}^3' for m in dev) or 'no mesh'}"
      + ("; the 32-case test cohort was opened once and its numbers are final." if test else
         "; the test cohort has **not** been opened.")
      + " **The bank is a 30-minute pilot fit frozen by a user decision taken after seeing its "
      "development floor (DESIGN A4)**, so bar (a) is relaxed and bar (b) is redefined relative to the "
      "floor; both deviations are marked where they are used. Generated by "
      "`reports/build_2026-10-01-ns3d-coordnet-bank.py` from the run JSONs.\n")

    # ----------------------------------------------------------- what was run --
    w("## What was run\n")
    w("The parents' co-moving reduced model is unchanged: $u(x,t)=v(x-c(t),t)$ with $v=G_n a$, the frame "
      "increment $\\delta=c^{n+1}-c^n$ solved every step from the same weak residual, tests the $M=292$ lowest "
      "divergence-free Fourier modes, implicit midpoint with $\\Delta t=0.02$ and 3 damped Gauss–Newton sweeps. "
      "Only the bank $G_n$ changes. It is one network $g_\\phi:\\mathbb T^3\\to\\mathbb R^{3\\times 64}$, "
      "$g=\\nabla\\times\\psi_\\phi$, with $\\psi_\\phi$ an MLP (4 SiLU layers of width 512) of integer-frequency "
      "Fourier features $\\sin,\\cos(2\\pi k\\cdot x)$, $\\max_i|k_i|\\le4$ — periodic by construction and "
      "divergence-free in the continuum. At mesh $n$ the bank is read as\n")
    w("$$G_n=\\mathrm{L\\ddot owdin}\\big(P_n\\,n^{-3/2}g_\\phi(x_n)\\,T\\big),$$\n")
    w("with $P_n$ the full-order solver's discrete space (two-thirds mask and Leray projection), $T$ the paper's "
      "QR+SVD importance ordering computed once from training states, and Löwdin the closest orthonormal matrix. "
      "The network was trained once on 3072 centred training states pooled across the three meshes "
      "(one third of the 512 trajectories at each mesh), by the variable-projection objective "
      "$1-\\lVert P_GY\\rVert_F^2/\\lVert Y\\rVert_F^2$ ($Y$ the weighted snapshot matrix compressed to 512 "
      "singular pairs). At each mesh the paper's $k=8$ head recipe is trained on $G_n^{\\mathsf T}$(centred "
      "training states) and the reduced model is run beside the paper's own POD-64 head, the CNAB2 ladder and the "
      "controls, in one allocation.\n")
    w("```mermaid\nflowchart LR\n"
      "  D[\"training states<br/>3 meshes, centred\"] --> TR[\"fit g_phi once<br/>(pilot, 30 min)\"]\n"
      "  TR --> F[\"frozen bank file<br/>phi and T\"]\n"
      "  F --> S32[\"read at 32^3\"] --> H32[\"head k=8\"] --> R32[\"ROM 32^3\"]\n"
      "  F --> S64[\"read at 64^3\"] --> H64[\"head k=8\"] --> R64[\"ROM 64^3\"]\n"
      "  F --> S96[\"read at 96^3\"] --> H96[\"head k=8\"] --> R96[\"ROM 96^3\"]\n"
      "  classDef trained fill:#fdf0e2,stroke:#b5762a,color:#4a2f0c;\n"
      "  classDef frozen fill:#e8eef7,stroke:#41618f,color:#12243d;\n"
      "  classDef solved fill:#eaf3ea,stroke:#4a7a4a,color:#1d3b1d;\n"
      "  class TR,H32,H64,H96 trained;\n  class F,S32,S64,S96 frozen;\n  class R32,R64,R96 solved;\n```\n")

    # ------------------------------------------------------------- bar (a) --
    w("## Bar (a): projection floor of the centred states\n")
    w("Oracle-centroid floor: each development state is centred on its own true energy centroid, projected on "
      "the bank and shifted back; evolved worst over the 16 development cases. POD-64 is the paper's bank, "
      "rebuilt in the same job. Pre-registered bar: coordnet ≤ 1.5 × POD-64 at every mesh. "
      "*A4 (user decision after the pilot): the floor is accepted at about 1 %; the pre-registered bar is "
      "evaluated and reported, not waived.*\n")
    w("| mesh | coordnet R=64 | POD-64 | ratio | coordnet prefixes R'=48 / 32 / 16 / 8 | job |")
    w("|---:|---:|---:|---:|---|---|")
    ratios = {}
    for m, s in dev.items():
        f = s["floors"]
        ratios[m] = f["coordnet_R64"]["evolved_worst"] / f["pod_R64"]["evolved_worst"]
        pre = " / ".join(pct(f[f"coordnet_R{p}"]["evolved_worst"]) for p in (48, 32, 16, 8))
        w(f"| {m}^3 | {pct(f['coordnet_R64']['evolved_worst'])} | {pct(f['pod_R64']['evolved_worst'])} | "
          f"{rx(ratios[m], 1)} | {pre} | {s['job_id']} |")
    w("")
    if pilot:
        fit = pilot["fits"]["A"]
        w(f"Training loss of the frozen fit {num(fit['final_train_loss'])} against the optimum "
          f"{num(fit['eckart_young_optimum'])} of the same objective at rank 64 (the weighted POD of the same data); "
          f"that optimum's own 32³ floor is {pct(pilot['floors']['32']['same_data_pod_R64']['evolved_worst'])} "
          "(pilot job), so the gap is the network fit, not the data.")
        if lfc:
            w(f" Independent local recomputation of the pilot's 32³ floors: largest relative gap "
              f"{num(max(v['relative_gap'] for v in lfc['floors'].values()))} (passed {lfc['passed']}).")
        w("\n")
    if ratios:
        w(f"**Bar (a) as pre-registered: {yes(all(r <= 1.5 for r in ratios.values()))}** "
          f"(worst ratio {rx(max(ratios.values()), 1)}). Accepted at about 1 % by the user decision of A4. "
          "The larger ranks that would have answered \"R needed to match POD-64\" were cancelled by the same "
          "decision; that number is **not measured**.\n")

    # -------------------------------------------------------- one bank? --
    w("## Does the frozen bank read the same on every mesh?\n")
    w("Sampling-only diagnostics of the frozen bank file (no flow data; `check_bank_meshes.py`) and the same "
      "quantities re-measured inside each mesh job.\n")
    w("| mesh | P_n removes (worst column) | pre-Löwdin max abs(GᵀG−I) | Löwdin column change | raw derivative mismatch (autodiff vs FFT) | D_d on the tests, autodiff vs FFT | restricted to 32³ vs read at 32³ (worst column) |")
    w("|---:|---:|---:|---:|---:|---:|---:|")
    for m in MESHES:
        sd = samp["meshes"][m] if samp else {}
        s = dev.get(m)
        b = s["coordnet_bank"] if s else sd
        w(f"| {m}^3 | {num(b.get('leray_removed_worst'))} | {num(b.get('orthonormality_before_lowdin'))} | "
          f"{num(b.get('lowdin_worst_column_change'))} | {num(sd.get('derivative_raw', {}).get('worst_column'))} | "
          f"{num(s['coordnet_Dd_autodiff_vs_spectral'] if s else None)} | "
          f"{num(sd.get('cross_mesh_vs_smallest', {}).get('worst_column'))} |")
    w("")
    if samp2:
        w(f"Read at 96³ and restricted to 64³ against read at 64³: worst column "
          f"{num(samp2['meshes']['96']['cross_mesh_vs_smallest']['worst_column'])}. "
          "The network carries energy above what a 32³ grid resolves: the 32³ reading differs from the finer "
          "readings by more than the finer ones differ from each other, and the autodiff/FFT derivative "
          "disagreement shrinks when the same network is read finer (aliasing, not a derivative error).\n")
    w("**Which derivative the frame uses.** $D_d=\\Phi^{\\mathsf T}\\partial_dG_n$ is the exact spectral derivative "
      "of the sampled, projected, Löwdin-orthonormalised bank actually used (on the periodic grid $G_n$ is a "
      "trigonometric polynomial). Every job checks it against a dense spectral derivative and against a central "
      "difference of the Fourier shift the frame applies:\n")
    w("| mesh | derivative check | shift-sign check | tensor check |")
    w("|---:|---:|---:|---:|")
    for m, s in dev.items():
        oc = s["operator_checks"]["coordnet"]
        w(f"| {m}^3 | {num(oc['derivative_relative'])} | {num(oc['shift_sign_relative'])} | {num(oc['tensor_relative'])} |")
    w("")

    # ------------------------------------------------------------ bars b, c --
    if dev:
        w("## The reduced model with the frozen bank (development, 16 cases)\n")
        w("Ladder setting ($\\Delta t=0.02$, 3 sweeps), nothing tuned for the coordnet bank. Comparator = the fastest "
          "stable CNAB2 setting whose evolved worst is no larger than the arm's, same job, one randomised "
          "interleaved timing block; speedup = its median / the arm's median.\n")
        w("| mesh | arm | unknowns | evolved worst | median | its floor | worst / floor | GPU ms | CNAB2 comparator | speedup |")
        w("|---:|---|---:|---:|---:|---:|---:|---:|---|---:|")
        for m, s in dev.items():
            f = s["floors"]
            for name, row in s["rollouts"].items():
                st, comp = row["stats"], s["comparators"].get(name, {})
                if name == hk:
                    fl, unk = f["coordnet_R64"]["evolved_worst"], K + 3
                elif name == "pod_head_k8":
                    fl, unk = f["pod_R64"]["evolved_worst"], 8 + 3
                elif name.startswith("coordnet_span"):
                    Rp = int(name[len("coordnet_span"):])
                    fl, unk = f[f"coordnet_R{Rp}"]["evolved_worst"], Rp + 3
                else:
                    fl, unk = f["pod_R64"]["evolved_worst"], 64 + 3
                cd = (f"{comp['comparator'].replace('CNAB2_s', 'CNAB2 ')} steps ({pct(comp['comparator_worst'])}, "
                      f"{comp['comparator_ms']:.1f} ms)" if comp.get("comparator") else "none as accurate")
                w(f"| {m}^3 | {name} | {unk} | {pct(st['evolved_worst']) if st else 'nonfinite'} | "
                  f"{pct(st['evolved_median']) if st else '—'} | {pct(fl)} | "
                  f"{rx(st['evolved_worst'] / fl) if st else '—'} | {comp.get('arm_ms', float('nan')):.2f} | {cd} | "
                  f"{rx(comp.get('speedup'))} |")
        w("")
        w("For the head, \"its floor\" is the coordnet bank's R=64 floor (the bar (b′) reference); the head's own "
          "achieved encoder floor is in the gates section.\n")
        # bar (b')
        bp = {}
        for m, s in dev.items():
            bp[m] = s["rollouts"][hk]["stats"]["evolved_worst"] / s["floors"]["coordnet_R64"]["evolved_worst"]
        sp96 = dev["96"]["comparators"][hk]["speedup"] if "96" in dev else None
        ok_b = bool(len(bp) == 3 and all(v <= 1.5 for v in bp.values()) and sp96 is not None and sp96 >= 5)
        w(f"**Bar (b′) (A4, user decision, fixed before the ROM jobs): {yes(ok_b)}.** Head worst / coordnet floor "
          + ", ".join(f"{m}^3 {rx(v)}" for m, v in bp.items()) + f" (bar ≤ 1.5x at every mesh); head at 96³ "
          f"{rx(sp96)} CNAB2 (bar ≥ 5x). The original bar (b) (≤ 0.25 % at 96³) "
          + (f"fails: {pct(dev['96']['rollouts'][hk]['stats']['evolved_worst'])}." if "96" in dev else "is not evaluated.") + "\n")
        # bar (c)
        if len(dev) == 3:
            hw = {m: dev[m]["rollouts"][hk]["stats"]["evolved_worst"] for m in MESHES}
            fw = {m: dev[m]["floors"]["coordnet_R64"]["evolved_worst"] for m in MESHES}
            od = {m: dev[m]["coordnet_bank"]["orthonormality_before_lowdin"] for m in MESHES}
            shas = {dev[m]["config"]["coordnet_bank_sha256"] for m in MESHES}
            hr = max(hw.values()) / min(hw.values())
            fr = max(fw.values()) / min(fw.values())
            c1, c2, c3, c4 = len(shas) == 1, hr <= 1.25, fr <= 1.25, max(od.values()) <= 1e-3
            w(f"**Bar (c) (unchanged, the main question): {yes(c1 and c2 and c3 and c4)}.** One bank file in all three "
              f"jobs: {c1}. Head evolved worst max/min over meshes {hr:.3f} (≤ 1.25: {c2}). Bank floor max/min "
              f"{fr:.3f} (≤ 1.25: {c3}). Pre-Löwdin deviation worst {num(max(od.values()))} (≤ 1e-3: {c4}; "
              "known to fail before the ROM jobs, A4).\n")
            phw = {m: dev[m]["rollouts"]["pod_head_k8"]["stats"]["evolved_worst"] for m in MESHES}
            w(f"For reference, the paper's per-mesh POD heads in the same jobs: max/min {max(phw.values()) / min(phw.values()):.3f}.\n")

    # ----------------------------------------------------------------- test --
    if test:
        w("## Test cohort (seed 202609221, 32 cases), opened once\n")
        w("All settings frozen in `experiments/ns3d-coordnet/frozen/frozen_settings.json` "
          f"(sha256 `{list(test.values())[0].get('frozen_settings_sha256')}`), committed before the job; the per-mesh "
          "coordnet heads are the development jobs' heads. Rounded-row overlap with training, development, "
          "202609203 and 202609211: "
          + ", ".join(f"{m}^3 {s.get('test_disjointness')}" for m, s in test.items()) + ".\n")
        w("| mesh | arm | evolved worst | median | over 5 % | worst / floor | GPU ms | CNAB2 comparator | speedup |")
        w("|---:|---|---:|---:|---:|---:|---:|---|---:|")
        for m, s in test.items():
            f = s["floors"]
            for name, row in s["rollouts"].items():
                st, comp = row["stats"], s["comparators"].get(name, {})
                fl = (f["coordnet_R64"] if name == hk else f["pod_R64"] if name.startswith("pod") else
                      f.get(f"coordnet_R{name[len('coordnet_span'):]}", {})).get("evolved_worst")
                cd = (f"{comp['comparator'].replace('CNAB2_s', 'CNAB2 ')} steps ({pct(comp['comparator_worst'])})"
                      if comp.get("comparator") else "none as accurate")
                w(f"| {m}^3 | {name} | {pct(st['evolved_worst'])} | {pct(st['evolved_median'])} | "
                  f"{st['cases_evolved_over_target']}/{st['cases']} | {rx(st['evolved_worst'] / fl) if fl else '—'} | "
                  f"{comp.get('arm_ms', float('nan')):.2f} | {cd} | {rx(comp.get('speedup'))} |")
        w("")
        if len(test) == 3:
            hw = {m: test[m]["rollouts"][hk]["stats"]["evolved_worst"] for m in MESHES}
            w(f"Test, coordnet head worst max/min over meshes {max(hw.values()) / min(hw.values()):.3f}; "
              "head worst / floor " + ", ".join(
                  f"{m}^3 {rx(hw[m] / test[m]['floors']['coordnet_R64']['evolved_worst'])}" for m in MESHES) + ".\n")

    # -------------------------------------------------------------- controls --
    w("## Controls (each must fail on real data)\n")
    w("| control | 32^3 | 64^3 | 96^3 | fails as required |")
    w("|---|---:|---:|---:|---|")
    if ff:
        v = {m: ff["floors"][m]["coordnet_fixed_frame_R64"]["evolved_worst"] for m in MESHES}
        w("| fixed-frame coordnet bank (trained on uncentred states, R=64, no shift anywhere) | "
          + " | ".join(pct(v[m], 2) for m in MESHES) + f" | {all(x > 0.05 for x in v.values())} |")
        v2 = {m: ff["floors"][m]["same_data_pod_fixed_frame_R64"]["evolved_worst"] for m in MESHES}
        w("| (reference) same-data POD-64 of the uncentred states | " + " | ".join(pct(v2[m], 2) for m in MESHES) + " | — |")
    if pilot:
        w(f"| frozen centred bank, development states not centred (pilot job) | "
          f"{pct(pilot['floors']['32']['coordnet_no_centring']['evolved_worst'], 2)} | — | — | "
          f"{pilot['floors']['32']['coordnet_no_centring']['evolved_worst'] > 0.05} |")
    for label, group in (("development", dev), ("test", test)):
        if group:
            w(f"| coordnet head with the frame frozen (δ ≡ 0), {label} | "
              + " | ".join(pct(group[m]["control_frame_zero"]["evolved_worst"], 2) if m in group else "—" for m in MESHES)
              + f" | {all(group[m]['control_frame_zero']['evolved_worst'] > 0.05 for m in group)} |")
    w("")
    if ff:
        w("The fixed-frame control was trained with the A3 recipe (band-limit penalty, 1.5 h), not the pilot "
          "recipe; it is a control of the frame, not of the fit.\n")

    # ----------------------------------------------------------------- gates --
    w("## Gates and audits\n")
    for label, group, ver in (("development", dev, devv), ("test", test, testv)):
        for m, s in group.items():
            v = ver.get(m) or {}
            rep = s.get("pod_reproduction") or {}
            diff = rep.get("max_abs_error_difference") or {}
            fa = v.get("floor_audit") or {}
            w(f"- **{label} {m}^3** (job {s['job_id']}, {s['gpu'].split(',')[0]}): gates `{s['status']}`. "
              f"POD reference reproduces its earlier job: max |Δerror| {num(max(diff.values()) if diff else None)} "
              f"(passed {rep.get('passed')}). POD bank rebuild gap {num(s['pod_bank_rebuild_gap'])}. "
              f"Coordnet head encoder floor {pct(s['floors'][f'coordnet_head_k{K}']['evolved_worst'])}. "
              f"Fixed-sweep vs generic LM {num(s['coordnet_head_parity_vs_lm']['worst'])}. "
              f"Timing gate {s['timing']['gate_passed']}; timed outputs vs accuracy pass "
              f"{num(s['timing']['timed_output_error_agreement'])}. NumPy audit passed {v.get('passed')} "
              f"(perturbed copy rejected {v.get('control_rejected')}; independent floor recomputation gap "
              f"{num(fa.get('relative_gap'))}). Flags: " + ("; ".join(s["failures"]) if s["failures"] else "none") + ".")
    w("")

    # -------------------------------------------------------- what went wrong --
    w("## What went wrong, what was changed, what is retracted\n")
    for item in plan["wrong"]:
        w(f"- {item}")
    if pilot:
        f = pilot["fits"]
        w(f"- Pilot job {pilot['job_id']}: three architectures, 30 min each; training losses "
          + ", ".join(f"{n} {num(v['final_train_loss'])}" for n, v in f.items())
          + ". Its real-mesh gates fired (32³ pre-Löwdin deviation "
          f"{num(pilot['floors']['32']['bank']['orthonormality_before_lowdin'])}, raw derivative mismatch "
          f"{num(pilot['floors']['32']['derivatives']['worst_column'])}). Architecture A's bank from this job is "
          "the frozen bank (A4).")
    w("")

    # ---------------------------------------------------------- the question --
    w("## Can the paper say \"one coordinate-network bank across meshes\"?\n")
    for para in plan["paper_answer"]:
        w(para + "\n")

    w("## Open\n")
    for item in plan["open"]:
        w(f"- {item}")
    w("")

    # ------------------------------------------------------------ provenance --
    w("## Provenance\n")
    w("| role | run | slurm id | GPU | source commit | summary sha256 |")
    w("|---|---|---:|---|---|---|")
    rows = []
    if pilot:
        rows.append(("pilot (frozen bank)", "pilot", RUNS / "pilot" / "output" / "summary.json", pilot))
    if ff:
        rows.append(("fixed-frame control", plan["fixed_frame_run"], RUNS / plan["fixed_frame_run"] / "output" / "summary.json", ff))
    for m, s in dev.items():
        rows.append((f"development {m}^3", plan["dev"][m], RUNS / plan["dev"][m] / "output" / "mesh" / "summary.json", s))
    for m, s in test.items():
        rows.append((f"test {m}^3", plan["test"], RUNS / plan["test"] / "output" / f"test{m}" / "summary.json", s))
    for role, run, path, s in rows:
        w(f"| {role} | `{run}` | {s['job_id']} | {s['gpu'].split(',')[0]} | `{(s['source_commit'] or '')[:10]}` | `{sha(path)[:16]}…` |")
    w("")
    bank = LANE / "banks" / "pilot" / "bank_selected.npz"
    w(f"Frozen bank file `experiments/ns3d-coordnet/banks/pilot/bank_selected.npz`, sha256 `{sha(bank)}`.")
    if frozen:
        w(f" Frozen test settings sha256 `{sha(LANE / 'frozen' / 'frozen_settings.json')}`.")
    w(" Jobs that never computed: " + "; ".join(plan["not_computed"]) + ".\n")

    # -------------------------------------------------------------- glossary --
    w("## Glossary\n")
    for term, text in (
        ("bank $G_n$", "the fixed spatial basis (here 64 vector fields) the reduced state lives in, read at mesh $n$."),
        ("coordinate network (coordnet)", "a neural network evaluated at a point $x$; it returns 64 vector fields at once, so reading it on any grid gives a bank."),
        ("vector potential / curl", "the network outputs $\\psi$; the bank is $\\nabla\\times\\psi$, whose divergence is zero."),
        ("POD-64", "the paper's bank: the best 64-dimensional linear basis, in mean square, of 768 centred training states, rebuilt at each mesh."),
        ("same-data POD", "the POD of exactly the data the coordnet was trained on: the best any 64-column bank can do on its training objective."),
        ("centred, co-moving frame, δ", "states are shifted so their energy centroid sits at the origin; the reduced model solves the shift increment δ at every step."),
        ("floor (oracle-centroid floor)", "error of the best reconstruction of a true state in the bank after centring it on its true centroid. A fixed reference, not a strict lower bound for a model that solves its own shift."),
        ("evolved worst / median", "per case, the largest relative $L^2$ error (relative to $\\lVert u_0\\rVert$) over the output times after $t=0$; then the worst / median over cases."),
        ("worst / floor", "an arm's evolved worst divided by the floor of the bank it lives in; 1 means the solve loses nothing beyond the bank."),
        ("over 5 %", "number of cases whose evolved worst exceeds 5 %."),
        ("prefix $R'$, span arm", "the first $R'$ columns of the importance-ordered bank; the span arm is the linear reduced model in them."),
        ("head $h$, $k$", "small network mapping $k=8$ numbers to the 64 bank coefficients; the paper's nonlinear trial manifold, trained per mesh."),
        ("Löwdin", "symmetric orthonormalisation $B(B^{\\mathsf T}B)^{-1/2}$; how much it changes the sampled bank measures how far that reading is from the trained bank."),
        ("$P_n$", "projection on the full-order solver's discrete space at mesh $n$: two-thirds dealiasing mask and divergence-free (Leray) projection."),
        ("pre-Löwdin deviation", "largest entry of $G^{\\mathsf T}G-I$ for the sampled bank before orthonormalisation; zero for a bank that reads identically on every mesh."),
        ("raw derivative mismatch", "relative difference between the network's automatic-differentiation derivatives at the grid nodes and FFT derivatives of its sampled values; large when the network has detail finer than the grid."),
        ("$D_d$", "the frame operator: tests applied to the $x_d$-derivative of every bank column."),
        ("CNAB2", "the pseudo-spectral full-order solver (Crank–Nicolson viscous, Adams–Bashforth-2 advection); truth at Δt = 0.001 and the speed comparator."),
        ("comparator / speedup", "the fastest stable CNAB2 setting at least as accurate as the arm; speedup = its median time / the arm's, from one interleaved timing block in the same job."),
        ("fixed-sweep vs generic LM", "difference between the 3-sweep Gauss–Newton query and a converged Levenberg–Marquardt reference on the same residual."),
        ("development / test", "the 16 cases used for every choice / the 32 cases evaluated once with everything frozen."),
        ("A3, A4", "amendments to the pre-registration; A4 is the user's decision, taken after the pilot, to freeze the pilot bank and change bars (a) and (b)."),
    ):
        w(f"- **{term}** — {text}")
    out = ROOT / "reports" / "2026-10-01-ns3d-coordnet-bank.md"
    out.write_text("\n".join(L) + "\n")
    print(out)


if __name__ == "__main__":
    main()
