"""Build reports/2026-10-01-ns3d-coordnet-bank.md from the pulled run JSONs of the
ns3d-coordnet lane. No number in the report is typed by hand.

Usage: /home/tahmid/Dev/.venv/bin/python reports/build_2026-10-01-ns3d-coordnet-bank.py
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LANE = ROOT / "experiments" / "ns3d-coordnet"
RUNS = LANE / "runs"
MESHES = ("32", "64", "96")
PLAN = json.loads((LANE / "results" / "report_plan.json").read_text())


def sha(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def load(path):
    p = Path(path)
    return json.loads(p.read_text()) if p.exists() else None


def pct(x, nd=3):
    return "—" if x is None else f"{100 * x:.{nd}f}%"


def num(x, fmt=".2e"):
    return "—" if x is None else format(x, fmt)


def ratio(x, nd=2):
    return "—" if x is None else f"{x:.{nd}f}x"


def main():
    sel = load(LANE / "results" / "bank_selection.json")
    banks = {k: load(RUNS / v / "output" / "summary.json") for k, v in PLAN["banks"].items()}
    pilot = load(RUNS / "pilot" / "output" / "summary.json")
    dev = {m: load(RUNS / PLAN["dev"][m] / "output" / "mesh" / "summary.json")
           for m in MESHES if m in PLAN.get("dev", {})}
    devv = {m: load(RUNS / PLAN["dev"][m] / "output" / "mesh" / "verify.json")
            for m in MESHES if m in PLAN.get("dev", {})}
    test = {m: load(RUNS / PLAN["test"] / "output" / f"test{m}" / "summary.json")
            for m in MESHES} if PLAN.get("test") else {}
    testv = {m: load(RUNS / PLAN["test"] / "output" / f"test{m}" / "verify.json")
             for m in MESHES} if PLAN.get("test") else {}
    dev = {m: s for m, s in dev.items() if s}
    test = {m: s for m, s in test.items() if s}
    L = []
    w = L.append
    k = 8

    # ------------------------------------------------------------- header --
    w("# NS3D: one coordinate-network bank inside the co-moving frame\n")
    stages = ["stage 1 (bank training and floors)"]
    if dev:
        stages.append("stage 2 (development ROM at " + ", ".join(f"{m}^3" for m in dev) + ")")
    if test:
        stages.append("stage 3 (test cohort, opened once)")
    stop = sel["stop"] if sel else None
    w("Lane `exp/2026-10-01-ns3d-coordnet-bank` asks whether **one** trained coordinate-network "
      "bank, sampled unchanged at $32^3$, $64^3$ and $96^3$, can replace the paper's per-mesh "
      "rank-64 centred POD bank inside the same co-moving frame, with the same $k=8$ head recipe "
      "and solver. Numbers below are final for: " + "; ".join(stages) + "."
      + (" Stage 1 met the pre-registered stop rule, so no ROM job was run." if stop else "")
      + " Generated by `reports/build_2026-10-01-ns3d-coordnet-bank.py` from the run JSONs; "
      "the pre-registration is `experiments/ns3d-coordnet/DESIGN.md` (amendments A1–A"
      + str(PLAN["last_amendment"]) + ").\n")

    # ------------------------------------------------------- what was run --
    w("## What was run\n")
    w("The co-moving form of the parent lanes is unchanged: $u(x,t)=v(x-c(t),t)$, $v=G_n a$, "
      "the frame increment $\\delta$ solved every step, tests the $M=292$ lowest "
      "divergence-free Fourier modes, implicit midpoint $\\Delta t=0.02$ with 3 damped "
      "Gauss–Newton sweeps. Only the bank changes. The bank is one network "
      "$g_\\phi:\\mathbb T^3\\to\\mathbb R^{3\\times R}$, $g=\\nabla\\times\\psi_\\phi$, with "
      "$\\psi_\\phi$ an MLP of integer-frequency Fourier features (periodic, exactly "
      "divergence-free in the continuum). At mesh $n$ the bank is\n")
    w("$$G_n=\\mathrm{L\\ddot owdin}\\big(P_n\\,n^{-3/2}g_\\phi(x_n)\\,T\\big),$$\n")
    w("$P_n$ the FOM's discrete space (2/3 mask + Leray), $T$ the paper's QR+SVD ordering "
      "computed once on training data, Löwdin the closest orthonormal matrix. It is trained once, "
      "on centred training states pooled across the three meshes, by the variable-projection "
      "objective plus a penalty on energy above $\\max_i|k_i|=10$ (DESIGN A3):\n")
    w("$$\\mathcal L(\\phi)=1-\\frac{\\lVert P_{G}Y\\rVert_F^2}{\\lVert Y\\rVert_F^2}"
      "+\\frac{\\lVert G-\\Pi_{10}G\\rVert_F^2}{\\lVert G\\rVert_F^2}.$$\n")
    w("```mermaid\nflowchart LR\n"
      "  D[\"training states, 3 meshes, centred\"] --> TR[\"train g_phi once (stage 1)\"]\n"
      "  TR --> ORD[\"ordering T (training data)\"]\n"
      "  ORD --> F[\"frozen bank file: phi, T\"]\n"
      "  F --> S32[\"sample at 32^3\"] --> R32[\"head k=8 + spans, ROM 32^3\"]\n"
      "  F --> S64[\"sample at 64^3\"] --> R64[\"head k=8 + spans, ROM 64^3\"]\n"
      "  F --> S96[\"sample at 96^3\"] --> R96[\"head k=8 + spans, ROM 96^3\"]\n"
      "  classDef trained fill:#fdf0e2,stroke:#b5762a,color:#4a2f0c;\n"
      "  classDef frozen fill:#e8eef7,stroke:#41618f,color:#12243d;\n"
      "  classDef solved fill:#eaf3ea,stroke:#4a7a4a,color:#1d3b1d;\n"
      "  class TR,ORD trained;\n  class F,S32,S64,S96 frozen;\n  class R32,R64,R96 solved;\n```\n")

    # ------------------------------------------------------------ bar (a) --
    w("## Bar (a): projection floor of the centred states\n")
    if sel:
        a = sel["bar_a"]
        w("Development cases (16), oracle centring (truth energy centroid per frame), evolved "
          "worst. POD-64 is the parent's bank rebuilt in the `R=64` bank job "
          f"(reproduces the parent jobs: {a['pod_reproduced']}). Pass bar: coordnet $R=64$ ≤ 1.5 × POD-64 "
          "at every mesh.\n")
        w("| bank | " + " | ".join(f"{m}^3 floor" for m in MESHES) + " | worst ratio to POD-64 | training loss | same-data optimum |")
        w("|---|" + "---:|" * 5)
        w("| POD-64 (paper) | " + " | ".join(pct(a["pod64_floor"][m]) for m in MESHES) + " | 1.00x | — | — |")
        for R in ("64", "128", "256"):
            s = banks.get(R)
            if not s:
                continue
            f = {m: s["floors"][m][f"coordnet_R{R}"]["evolved_worst"] for m in MESHES}
            fit = s["fits"][s["selected_architecture"]]
            w(f"| coordnet R={R} | " + " | ".join(pct(f[m]) for m in MESHES)
              + f" | {ratio(max(f[m] / a['pod64_floor'][m] for m in MESHES))} | "
              f"{num(fit['final_train_loss'])} | {num(fit['eckart_young_optimum'])} |")
        s = banks.get("64")
        if s:
            f = {m: s["floors"][m]["same_data_pod_R64"]["evolved_worst"] for m in MESHES}
            w("| same-data weighted POD, R=64 (optimum of the training objective) | "
              + " | ".join(pct(f[m]) for m in MESHES)
              + f" | {ratio(max(f[m] / a['pod64_floor'][m] for m in MESHES))} | — | — |")
        w("")
        w(f"**Verdict (a): {'PASS' if a['passed'] else 'FAIL'}.** Coordnet $R=64$ / POD-64 at "
          + ", ".join(f"{m}^3 {ratio(a['ratio'][m])}" for m in MESHES)
          + f". Smallest trained $R$ whose floor is at or below POD-64 at every mesh: "
          f"**{a['R_needed_to_match_pod64']}**.\n")
        w("Ordered prefixes $R'$ of each bank (the span knob), worst over meshes:\n")
        w("| bank | " + " | ".join(f"R'={p}" for p in (8, 16, 32, 48, 64, 128, 192)) + " |")
        w("|---|" + "---:|" * 7)
        for R in ("64", "128", "256"):
            s = banks.get(R)
            if not s:
                continue
            cells = []
            for p in (8, 16, 32, 48, 64, 128, 192):
                key = f"coordnet_R{p}"
                cells.append(pct(max(s["floors"][m][key]["evolved_worst"] for m in MESHES))
                             if key in s["floors"]["32"] else "—")
            w(f"| coordnet R={R} | " + " | ".join(cells) + " |")
        w("")
        if sel["selected"]:
            c = sel["selected"]
            w(f"**ROM bank selected by the pre-registered rule:** the first {c['columns']} ordered "
              f"columns of the R={c['parent_rank']} bank ({'dedicated' if c['dedicated'] else 'prefix'}), "
              f"worst floor {pct(c['worst'])}, tier {sel['selection_tier']}.\n")
        else:
            w("**No bank or prefix reached 0.25 % at every mesh: the lane stopped after stage 1** "
              "(bars (b) and the head part of (c) are *not evaluated*; the head's error stays near "
              "its bank's floor in every parent run, so they could not have passed).\n")

    # ------------------------------------------------------- consistency --
    w("## Is it one bank on every mesh?\n")
    w("Per bank and mesh: energy the mesh's $P_n$ removes (worst column), distance from "
      "orthonormal before Löwdin ($\\max|G^{\\mathsf T}G-I|$), the column change Löwdin makes, the "
      "cross-mesh discrepancy (bank sampled at $n$ restricted to $32^3$ vs sampled at $32^3$, "
      "worst column), autodiff vs spectral derivatives of the raw sampled columns, and the "
      "trained bank's energy fraction above the band.\n")
    w("| bank | mesh | P_n removed | pre-Löwdin deviation | Löwdin change | cross-mesh vs 32^3 | derivative mismatch | band fraction |")
    w("|---|---:|---:|---:|---:|---:|---:|---:|")
    for R in ("64", "128", "256"):
        s = banks.get(R)
        if not s:
            continue
        band = s["fits"][s["selected_architecture"]].get("band_fraction")
        for m in MESHES:
            e = s["floors"][m]
            b = e["bank"]
            cm = e.get("cross_mesh_vs_smallest", {}).get("worst_column")
            dv = e.get("derivatives", {}).get("worst_column")
            w(f"| R={R} | {m}^3 | {num(b['leray_removed_worst'])} | {num(b['orthonormality_before_lowdin'])} | "
              f"{num(b['lowdin_worst_column_change'])} | {num(cm)} | {num(dv)} | {num(band)} |")
    w("")

    # ----------------------------------------------------------- controls --
    w("## Controls (each must fail on real data)\n")
    if sel:
        c = sel["controls"]
        w("| control | " + " | ".join(f"{m}^3" for m in MESHES) + " | fails as required |")
        w("|---|" + "---:|" * 3 + "---|")
        w("| fixed-frame coordnet bank (trained on uncentred states, R=64), no shift | "
          + " | ".join(pct(c["fixed_frame_floor"][m], 2) for m in MESHES) + f" | {c['fixed_frame_fails']} |")
        for R, d in c["no_centring_floor"].items():
            w(f"| centred coordnet R={R}, development states not centred | "
              + " | ".join(pct(d[m], 2) for m in MESHES) + f" | {all(v > 0.05 for v in d.values())} |")
        if dev:
            w("| coordnet head with the frame frozen (δ ≡ 0) | "
              + " | ".join(pct(dev[m]["control_frame_zero"]["evolved_worst"], 2) if m in dev else "—" for m in MESHES)
              + f" | {all(dev[m]['control_frame_zero']['evolved_worst'] > 0.05 for m in dev)} |")
        w("")

    # ----------------------------------------------------- bars (b), (c) --
    if dev:
        w("## Bars (b) and (c): the ROM with the frozen coordnet bank (development)\n")
        w("Ladder setting $\\Delta t=0.02$, 3 sweeps, nothing tuned for the coordnet bank. "
          "Comparator = fastest stable CNAB2 setting no less accurate than the arm, same job, "
          "interleaved timing block; speedup = its median / the arm's median.\n")
        w("| mesh | arm | unknowns | worst | median | floor | GPU ms | CNAB2 comparator | speedup | job |")
        w("|---:|---|---:|---:|---:|---:|---:|---|---:|---|")
        for m, s in dev.items():
            for name, row in s["rollouts"].items():
                comp = s["comparators"].get(name, {})
                st = row["stats"]
                if name.startswith("coordnet_head"):
                    fl, unk = s["floors"].get(f"coordnet_head_k{k}", {}).get("evolved_worst"), k + 3
                elif name.startswith("pod_head"):
                    fl, unk = s["floors"].get("pod_head_k8", {}).get("evolved_worst"), 8 + 3
                elif name.startswith("coordnet_span"):
                    Rp = int(name[len("coordnet_span"):])
                    fl, unk = s["floors"].get(f"coordnet_R{Rp}", {}).get("evolved_worst"), Rp + 3
                else:
                    fl, unk = s["floors"]["pod_R64"]["evolved_worst"], 64 + 3
                cdesc = (f"{comp['comparator']} ({pct(comp['comparator_worst'])}, {comp['comparator_ms']:.2f} ms)"
                         if comp.get("comparator") else "none as accurate")
                w(f"| {m}^3 | {name} | {unk} | {pct(st['evolved_worst']) if st else 'nonfinite'} | "
                  f"{pct(st['evolved_median']) if st else '—'} | {pct(fl)} | "
                  f"{comp.get('arm_ms', float('nan')):.2f} | {cdesc} | {ratio(comp.get('speedup'))} | {s['job_id']} |")
        w("")
        hk = f"coordnet_head_k{k}"
        if "96" in dev:
            r = dev["96"]["rollouts"][hk]["stats"]["evolved_worst"]
            sp = dev["96"]["comparators"][hk]["speedup"]
            ok_b = bool(r <= 0.0025 and sp is not None and sp >= 5)
            w(f"**Verdict (b): {'PASS' if ok_b else 'FAIL'}.** Coordnet head $k=8$ at $96^3$: "
              f"{pct(r)} evolved worst (bar ≤ 0.25 %; paper POD head in the same job "
              f"{pct(dev['96']['rollouts']['pod_head_k8']['stats']['evolved_worst'])}) at "
              f"{ratio(sp)} CNAB2 (bar ≥ 5x).\n")
        if len(dev) == 3:
            hw = {m: dev[m]["rollouts"][hk]["stats"]["evolved_worst"] for m in MESHES}
            fw = {m: dev[m]["floors"][f"coordnet_R{dev[m]['coordnet_bank'].get('prefix') or sel['selected']['columns']}"]["evolved_worst"]
                  for m in MESHES}
            hr, fr = max(hw.values()) / min(hw.values()), max(fw.values()) / min(fw.values())
            od = {m: dev[m]["coordnet_bank"]["orthonormality_before_lowdin"] for m in MESHES}
            shas = {dev[m]["config"]["coordnet_bank_sha256"] for m in MESHES}
            ok_c = bool(hr <= 1.25 and fr <= 1.25 and max(od.values()) <= 1e-3 and len(shas) == 1)
            w(f"**Verdict (c): {'PASS' if ok_c else 'FAIL'}.** One bank file in all three jobs "
              f"({len(shas) == 1}); head worst max/min over meshes {hr:.3f} (bar ≤ 1.25); bank floor "
              f"max/min {fr:.3f} (bar ≤ 1.25); pre-Löwdin deviation worst {num(max(od.values()))} "
              "(bar ≤ 1e-3).\n")

    # ---------------------------------------------------------------- test --
    if test:
        w("## Test cohort (seed 202609221, 32 cases, opened once by this lane)\n")
        w("Every setting frozen in `experiments/ns3d-coordnet/frozen/frozen_settings.json` "
          f"(sha256 `{list(test.values())[0].get('frozen_settings_sha256')}`) before the job.\n")
        w("| mesh | arm | worst | median | over 5 % | GPU ms | CNAB2 comparator | speedup |")
        w("|---:|---|---:|---:|---:|---:|---|---:|")
        for m, s in test.items():
            for name, row in s["rollouts"].items():
                st, comp = row["stats"], s["comparators"].get(name, {})
                cdesc = (f"{comp['comparator']} ({pct(comp['comparator_worst'])})"
                         if comp.get("comparator") else "none as accurate")
                w(f"| {m}^3 | {name} | {pct(st['evolved_worst'])} | {pct(st['evolved_median'])} | "
                  f"{st['cases_evolved_over_target']}/{st['cases']} | {comp.get('arm_ms', float('nan')):.2f} | "
                  f"{cdesc} | {ratio(comp.get('speedup'))} |")
        w("")

    # --------------------------------------------------------------- gates --
    w("## Gates and audits\n")
    for R, s in banks.items():
        if s:
            w(f"- bank R={R} (job {s['job_id']}): status `{s['status']}`; flags: "
              + ("; ".join(s["failures"]) if s["failures"] else "none") + ".")
    for label, group, ver in (("development", dev, devv), ("test", test, testv)):
        for m, s in group.items():
            v = ver.get(m) or {}
            rep = s.get("pod_reproduction", {})
            w(f"- {label} {m}^3 (job {s['job_id']}): status `{s['status']}`; POD reproduction "
              f"max |Δerror| {num(max(rep.get('max_abs_error_difference', {0: None}).values()) if rep else None)} "
              f"(passed {rep.get('passed')}); LM parity {num(s['coordnet_head_parity_vs_lm']['worst'])}; "
              f"D_d autodiff vs spectral {num(s['coordnet_Dd_autodiff_vs_spectral'])}; timing gate "
              f"{s['timing']['gate_passed']}; timed-output agreement {num(s['timing']['timed_output_error_agreement'])}; "
              f"NumPy audit passed {v.get('passed')} (perturbed copy rejected {v.get('control_rejected')}); "
              "flags: " + ("; ".join(s["failures"]) if s["failures"] else "none") + ".")
    w("")

    # --------------------------------------------------- what went wrong --
    w("## What went wrong, and what was changed before the production jobs\n")
    for item in PLAN["wrong"]:
        w(f"- {item}")
    if pilot:
        f = pilot["fits"]
        w(f"- Pilot job {pilot['job_id']} (30 min per architecture): training losses "
          + ", ".join(f"{n} {num(v['final_train_loss'])}" for n, v in f.items())
          + f"; its 32³ floor at R=64 was {pct(pilot['floors']['32']['coordnet_R64']['evolved_worst'])} against "
          f"POD-64 {pct(pilot['floors']['32']['parent_pod_R64']['evolved_worst'])}, with pre-Löwdin deviation "
          f"{num(pilot['floors']['32']['bank']['orthonormality_before_lowdin'])} and derivative mismatch "
          f"{num(pilot['floors']['32']['derivatives']['worst_column'])} — the reason for the band penalty (A3). "
          "Not a bar (a) result.")
    w("")

    # ------------------------------------------------------ paper sentence --
    w("## Can the paper say \"one coordinate-network bank across meshes\"?\n")
    w(PLAN.get("paper_answer_intro", ""))
    w("")

    # ---------------------------------------------------------- provenance --
    w("## Provenance\n")
    w("| role | run | slurm id | GPU | commit | summary sha256 |")
    w("|---|---|---:|---|---|---|")
    rows = [(f"bank R={R}", PLAN["banks"][R], s) for R, s in banks.items() if s]
    rows += [("pilot", "pilot", pilot)] if pilot else []
    rows += [(f"dev {m}^3", PLAN["dev"][m], s) for m, s in dev.items()]
    rows += [(f"test {m}^3", PLAN.get("test"), s) for m, s in test.items()]
    for role, run, s in rows:
        path = (RUNS / run / "output" / "summary.json") if role.startswith(("bank", "pilot")) else (
            RUNS / run / "output" / ("mesh" if role.startswith("dev") else f"test{role.split()[1][:2]}") / "summary.json")
        w(f"| {role} | `{run}` | {s['job_id']} | {s['gpu'].split(',')[0]} | `{(s['source_commit'] or '')[:10]}` | `{sha(path)[:16]}…` |")
    w("")
    w("Jobs that failed the GPU preflight (node pax007, no CUDA device; no computation): "
      + ", ".join(PLAN["failed_preflight"]) + ".\n")

    # ------------------------------------------------------------ glossary --
    w("## Glossary\n")
    for term, text in (
        ("bank $G_n$", "the fixed spatial basis the reduced state lives in, read at mesh $n$."),
        ("coordinate network (coordnet)", "a neural network evaluated at a point $x$; here it returns $R$ vector fields, so reading it on any grid gives a bank."),
        ("vector potential / curl", "the network outputs $\\psi$; the bank is $\\nabla\\times\\psi$, which has zero divergence."),
        ("POD-64", "the paper's bank: the best 64-dimensional linear basis (in mean square) of 768 centred training states, rebuilt per mesh."),
        ("same-data POD", "the POD of the exact data the coordnet is trained on; the best any rank-$R$ bank can do on the training objective."),
        ("centred, co-moving frame, δ", "states are shifted so their energy centroid sits at the origin; the ROM solves the shift increment δ every step."),
        ("floor", "error of the best reconstruction of a true state in the bank after centring on its true centroid; a fixed reference, not a strict lower bound for a ROM that solves its own shift."),
        ("evolved worst / median", "per case, the largest relative $L^2$ error (relative to $\\lVert u_0\\rVert$) over the output times after $t=0$; then the worst / median over cases."),
        ("over 5 %", "number of cases whose evolved worst exceeds 5 %."),
        ("ordering $T$, prefix $R'$", "a fixed rotation of the bank sorting its columns by how much training data they carry; $R'$ = how many leading columns are used (the span knob)."),
        ("Löwdin", "symmetric orthonormalisation $B(B^{\\mathsf T}B)^{-1/2}$; its size measures how far the sampled bank is from the trained one."),
        ("$P_n$", "projection on the full-order solver's discrete space at mesh $n$ (two-thirds dealiasing mask and divergence-free projection)."),
        ("band fraction", "share of the trained bank's energy above Fourier index 10 on the training grid; small means the network reads the same on every mesh."),
        ("cross-mesh discrepancy", "bank sampled at a fine mesh, spectrally restricted to $32^3$, compared with the bank sampled at $32^3$ directly."),
        ("derivative mismatch", "relative difference between the network's automatic-differentiation derivatives and FFT derivatives of its sampled columns; large means energy above the grid's resolution."),
        ("head $h$, $k$", "small network mapping $k$ numbers to bank coefficients; the paper's nonlinear trial manifold."),
        ("span arm", "the linear reduced model in the first $R'$ ordered bank columns."),
        ("CNAB2", "the pseudo-spectral full-order solver (Crank–Nicolson viscous, Adams–Bashforth-2 advection); truth at Δt = 0.001 and the speed comparator."),
        ("comparator / speedup", "the fastest stable CNAB2 setting at least as accurate as the arm; speedup = its median time / the arm's, from one interleaved timing block."),
        ("development / test", "the 16 cases used for every choice / the 32 cases evaluated once with everything frozen."),
        ("fixed-frame control", "a coordnet bank trained and used without any centring; it must miss 5 % by far."),
    ):
        w(f"- **{term}** — {text}")
    out = ROOT / "reports" / "2026-10-01-ns3d-coordnet-bank.md"
    out.write_text("\n".join(L) + "\n")
    print(out)


if __name__ == "__main__":
    main()
