#!/usr/bin/env python3
"""Burgers and Poisson tables with the tensor / quadrature-free arms, as one short markdown file.

Reuses the extraction of `gen_2026-09-03-separable-decoder-digest.py`: every table is copied
verbatim from its source report (all generated from run JSONs).  Nothing is typed here.

    /home/tahmid/Dev/.venv/bin/python reports/gen_2026-09-03-burgers-poisson-tensor-tables.py
"""
from pathlib import Path
import importlib.util
import sys

HERE = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("digest", HERE / "gen_2026-09-03-separable-decoder-digest.py")
digest = importlib.util.module_from_spec(spec)
sys.modules["digest"] = digest
spec.loader.exec_module(digest)
T = digest.T

OUT = HERE / "2026-09-03-burgers-poisson-tensor-tables.md"

DOC = f"""# Burgers and Poisson: the tensor and quadrature-free tables

The Burgers 1D/2D and Poisson 2D tables with the sample-free arms (quadratic tensor for Burgers,
quadrature-free residual for Poisson), pulled out of `2026-09-03-separable-decoder-results-digest.md`
so they can be read on their own. Numbers are **final** for these checkpoints (single seed).
Every table is copied verbatim from the source report named under it, whose tables are generated
from run JSONs; nothing here is typed by hand. Generated by
`gen_2026-09-03-burgers-poisson-tensor-tables.py`.

## Burgers 2D

The current headline speed protocol (K=32, matched-accuracy paired AB/BA against the swept
Helmholtz-preconditioned Newton ladder). This replaced the retracted four-resolution speedups.

{T["x1"]}

*Source: `2026-08-26-exact-linear-terms-and-gradient-eq.md` (`gen_2026-08-26-exlin.py`).*

The tensor arm: advection projected exactly through a precomputed quadratic form, nothing sampled,
nothing fitted.

{T["b2t4"]}

{T["b2t10"]}

{T["b2t7"]}

*Source: `2026-08-30-b2d-tensor-ladder.md` (`gen_2026-08-30-b2d-tensor.py`). The GPU differs
across rows; cross-N values are ratios, not exponents.*

## Burgers 1D

Tensor arm on one A100 with the resolutions interleaved in one job, then the fitted cost
exponents from that job alone.

{T["b1t2"]}

{T["b1t8"]}

*Source: `2026-08-29-b1d-tensor-sample-free-burgers.md` (`gen_2026-08-29-b1d-tensor.py`).*

Where the optimised 1D rollout stands against the tridiagonal tolerance-Newton FOM. Not
iso-accuracy: the FOM is far more accurate at every N.

{T["o2"]}

*Source: `2026-08-28-b1d-rollout-optimization.md` (`gen_2026-08-27-b1d-nodes-and-poisson-qf.py`).*

## Poisson 2D

The three residual paths through the same solver: full grid, sampled (EQ), and quadrature-free.

{T["pp1"]}

{T["pp2"]}

{T["pp3"]}

*Source: `2026-08-27-b1d-node-screening-and-poisson-qf.md`
(`gen_2026-08-27-b1d-nodes-and-poisson-qf.py`).*

ROM against the CG ladder across N. The CG rung is unpreconditioned, so the lab log marks these
speedups as soft; a spectral direct solve beats both.

{T["p1"]}

*Source: `2026-08-25-poisson-architecture-and-results.md` (`gen_2026-08-25-poisson-summary.py`).*

## Glossary

- **full / oracle**: residual evaluated on the whole grid, no quadrature.
- **ex / exact-linear**: linear residual terms computed exactly through $A = \\Phi^{{\\mathsf T}} G$;
  advection still sampled at NNLS nodes.
- **tensor**: advection term projected exactly, $\\Phi^{{\\mathsf T}}(u \\odot D u) = \\tfrac12 h^{{\\mathsf T}} Q h$.
- **ex_learned / learned-32**: the sampled arm with learned node positions.
- **NNLS-32**: sampled arm with 32 nodes fitted by non-negative least squares.
- **eq / qf**: sampled empirical quadrature / quadrature-free (Poisson).
- **e2e**: end to end, including the initial-condition fit and the full-grid decode.
- **matched rung**: cheapest FOM tolerance setting at least as accurate as the ROM arm.
- **(b), (c1), cos**: residual error, gradient error, and gradient direction agreement against
  the full grid.
- **paired / AB/BA**: ROM and FOM timed alternately in one job on one GPU.
"""

OUT.write_text(DOC)
print(f"wrote {OUT.name} ({len(DOC.splitlines())} lines)")
