"""Cross-PDE online-cost ladders for the study deck
(reports/2026-08-29-study-deck-linear-vs-nonlinear-residuals.tex).

Emits LaTeX ``tabular`` fragments into reports/tables/.  Every number is read
out of a run JSON; nothing is hand-typed.  The one exception is flagged
explicitly below (the Heat aggregate ratio, which exists only as prose in a
generated report and is parsed, not retyped).

    /home/tahmid/Dev/.venv/bin/python reports/gen_2026-08-30-cross-pde-cost.py

Sources
-------
1D Burgers   worktrees/2026-08-29-b1d-tensor/experiments/separable-decoder/
             runs/b1dtensor/ladder1/out/sep_b1d_ladder.json          (JOB A: one
             GPU, one process, N interleaved -> comparable across N)
             runs/b1dtensor/tensor_n{16384,65536}/out/
             sep_b1d_tensor_n*.json                                  (separate
             jobs -> marked cross-job)
2D Burgers   worktrees/2026-08-29-b2d-tensor/experiments/separable-decoder/
             runs/b2dtensor/n{64,256,512,1024}/out/sep_b2d_tensor_n*.json
             (one job per N, and a DIFFERENT GPU per N -- the GPU model is
             carried into the table as its own column, because the across-N
             trend otherwise silently mixes hardware)
Stokes       worktrees/2026-08-30-stokes-vector/experiments/separable-decoder/
             runs/stk2d/stk2d_rom_gates_rom_nu1.json, gate S7, "times" block
Poisson      worktrees/2026-08-27-b1d-poissonqf/experiments/separable-decoder/
             runs/b1dqf/qf_n{128,256,512}/out/sep_poisson_qf_*.json
Heat         NO per-N cost ladder exists in any run JSON of this project.  Only
             an aggregate direct-POD-Galerkin-vs-FOM ratio, and it lives as
             PROSE in reports/2026-08-17-four-pde-results-illustrated.md, whose
             numbers were themselves generated.  It is PARSED with a regex from
             that file (see heat_ratio()); it is never typed here.  Every
             per-N Heat cell is emitted as "not measured".
Waves        No cost ladder at all: the cell was retired without implementation
             (LAB-LOG.md, exp/2026-08-30-waves-vector, WAVES-RETIRED.md).
             Emitted as "not measured".
"""
from __future__ import annotations

import glob
import json
import os
import re

ROOT = "/home/tahmid/Dev/pod-ae-nmrom/Tunable-NM-ROM-Claude"
WT = os.path.join(ROOT, "worktrees")
OUT = os.path.join(ROOT, "reports", "tables")

B1D = os.path.join(WT, "2026-08-29-b1d-tensor", "experiments",
                   "separable-decoder", "runs", "b1dtensor")
B2D = os.path.join(WT, "2026-08-29-b2d-tensor", "experiments",
                   "separable-decoder", "runs", "b2dtensor")
STK = os.path.join(WT, "2026-08-30-stokes-vector", "experiments",
                   "separable-decoder", "runs", "stk2d",
                   "stk2d_rom_gates_rom_nu1.json")
PQF = os.path.join(WT, "2026-08-27-b1d-poissonqf", "experiments",
                   "separable-decoder", "runs", "b1dqf")
HEAT_REPORT = os.path.join(ROOT, "reports",
                           "2026-08-17-four-pde-results-illustrated.md")

NM = r"\textit{\footnotesize not measured}"   # never invent, never interpolate


def load(path):
    with open(path) as fh:
        return json.load(fh)


def gpu_short(s):
    """Shorten a CUDA device name for a table cell (no information dropped
    that distinguishes the cards used here)."""
    s = s.replace("NVIDIA ", "")
    s = s.replace("A100 80GB PCIe", "A100-80GB").replace("A100-PCIE-40GB",
                                                         "A100-40GB")
    return s


def w(name, text):
    os.makedirs(OUT, exist_ok=True)
    p = os.path.join(OUT, name)
    with open(p, "w") as fh:
        fh.write("% GENERATED by reports/gen_2026-08-30-cross-pde-cost.py "
                 "-- do not edit by hand.\n")
        fh.write(text.rstrip() + "\n")
    print(f"wrote {os.path.relpath(p, ROOT)}")


# ---------------------------------------------------------------- 1D Burgers
def burgers_1d():
    L = load(os.path.join(B1D, "ladder1", "out", "sep_b1d_ladder.json"))
    assert L["complete"], "ladder JOB A incomplete"
    cfg = L["config"]
    gpu = gpu_short(cfg["gpu"])
    ns = sorted(int(n) for n in L["cells"])

    big = {}
    for p in sorted(glob.glob(os.path.join(B1D, "tensor_n*", "out",
                                           "sep_b1d_tensor_n*.json"))):
        n = int(re.search(r"_n(\d+)\.json$", p).group(1))
        if n > 4096:
            d = load(p)
            assert d["complete"], f"incomplete: {p}"
            big[n] = d

    rows = []
    for n in ns:
        c = L["cells"][str(n)]
        rows.append(f"    {n} & {c['oracle']['roll_ms']:.1f} & "
                    f"{c['base_tight']['roll_ms']:.1f} & "
                    f"\\textbf{{{c['tensor']['roll_ms']:.1f}}} \\\\")
    f = L["fits"]
    rows.append(r"    \midrule")
    rows.append("    exponent $p$ & "
                f"${f['oracle:roll_ms']['exponent']:+.2f}$ & "
                f"${f['base_tight:roll_ms']['exponent']:+.2f}$ & "
                f"$\\mathbf{{{f['tensor:roll_ms']['exponent']:+.2f}}}$ \\\\")

    big_rows = []
    for n in sorted(big):
        d = big[n]
        v = d["variants"]
        g = gpu_short(d["config"]["gpu"])
        big_rows.append(f"    {n:,} & {g} & {v['oracle']['roll_fast_ms']:.1f} & "
                        f"{v['base_tight']['roll_fast_ms']:.1f} & "
                        f"\\textbf{{{v['tensor']['roll_fast_ms']:.1f}}} \\\\"
                        .replace(",", "\\,"))

    tex = f"""{{\\footnotesize\\textbf{{One job, one {gpu}, $N$ interleaved}}
  (job {cfg['slurm_job']}) --- latent-solve ms per 50-step trajectory}}\\par\\vspace{{1mm}}
\\begin{{tabular}}{{@{{}}rrrr@{{}}}}
  \\toprule
  $N$ & full-grid oracle & NNLS-32 & \\textbf{{tensor}}\\\\
  \\midrule
{chr(10).join(rows)}
  \\bottomrule
\\end{{tabular}}
\\vspace{{2mm}}

{{\\footnotesize\\textbf{{Beyond the launch floor --- \\emph{{separate jobs}}:
  cross-job figures, not a fitted exponent}}}}\\par\\vspace{{1mm}}
\\begin{{tabular}}{{@{{}}rlrrr@{{}}}}
  \\toprule
  $N$ & GPU & full-grid oracle & NNLS-32 & \\textbf{{tensor}}\\\\
  \\midrule
{chr(10).join(big_rows)}
  \\bottomrule
\\end{{tabular}}"""
    w("cross-pde-cost-b1d.tex", tex)


# ---------------------------------------------------------------- 2D Burgers
def burgers_2d():
    jobs = {}
    for p in sorted(glob.glob(os.path.join(B2D, "n*", "out",
                                           "sep_b2d_tensor_n*.json"))):
        d = load(p)
        c = d["config"]
        # the R=512 stretch job (n1024r512) is a different configuration and
        # did not complete -- it is not part of this ladder.
        if not d.get("complete") or "arms_run" not in c:
            continue
        n = int(re.search(r"_n(\d+)\.json$", p).group(1))
        jobs[n] = d
    jobs = dict(sorted(jobs.items()))

    rows = []
    gpus = set()
    for n, d in jobs.items():
        v = d["variants"]
        g = gpu_short(d["config"]["gpu"])
        gpus.add(g)
        rows.append(f"    {n} & {g} & {d['config']['slurm_job']} & "
                    f"{v['full']['roll_ms_median']:.1f} & "
                    f"{v['ex']['roll_ms_median']:.1f} & "
                    f"\\textbf{{{v['tensor']['roll_ms_median']:.1f}}} & "
                    f"{v['tensor']['roll_ms_median']/v['full']['roll_ms_median']:.3f} & "
                    f"{v['tensor']['roll_ms_median']/v['ex']['roll_ms_median']:.3f} \\\\")

    tex = f"""\\begin{{tabular}}{{@{{}}rllrrrrr@{{}}}}
  \\toprule
  $N$ & \\textbf{{GPU}} & job & full grid & exact-lin.\\,$+$\\,NNLS &
  \\textbf{{tensor}} & tensor/full & tensor/NNLS\\\\
  \\midrule
{chr(10).join(rows)}
  \\bottomrule
\\end{{tabular}}

\\vspace{{1.5mm}}
{{\\footnotesize\\textbf{{Read the GPU column first: {len(gpus)} different cards
across {len(jobs)} rungs.}} Each $N$ is its own job on its own node, so the
tensor/full and tensor/NNLS \\emph{{ratios}} (measured inside one job) are sound,
while the raw ms \\emph{{across}} rows mix hardware and are not an exponent.}}"""
    w("cross-pde-cost-b2d.tex", tex)


# -------------------------------------------------------------------- Stokes
def stokes():
    d = load(STK)
    assert d.get("complete", True)
    s7 = d["gates"]["S7"]
    rows = []
    for r in s7["rows"]:
        t = r["times"]

        def med(k):
            return t[k]["median"]

        rows.append(
            f"    {r['N']} & {med('fom_backsub'):.4f} & "
            f"{med('rom_fullgrid_nonlinear'):.4f} & "
            f"{med('rom_eq_nonlinear'):.4f} & "
            f"\\textbf{{{med('rom_qf_nonlinear'):.4f}}} & "
            f"{med('rom_gspan_direct')*1e6:.1f}\\,$\\mu$s & "
            f"{med('rom_qf_nonlinear')/med('rom_gspan_direct'):.0f}$\\times$ \\\\")

    dev = d["config"]["jax"]["device_kind"]
    reps = d["config"]["reps"]
    tex = f"""\\begin{{tabular}}{{@{{}}rrrrrrr@{{}}}}
  \\toprule
  $N$ & FOM & full-grid ROM & EQ ROM & \\textbf{{quad.-free ROM}} &
  direct $G$-span & \\multicolumn{{1}}{{c}}{{QF\\,/\\,$G$-span}}\\\\
  \\midrule
{chr(10).join(rows)}
  \\bottomrule
\\end{{tabular}}

\\vspace{{1.5mm}}
{{\\footnotesize Seconds per query (median of {reps} timed reps, gate S7); every
timed path is NumPy on CPU, host {dev}. The FOM column is the
back-substitution of a pre-factored MAC system, i.e.\\ the \\emph{{cheapest
honest}} full-order query.}}"""
    w("cross-pde-cost-stokes.tex", tex)


def stokes_results():
    """Exactness (gate S4 + the S7 pressure-elimination rung) and accuracy
    (gate S7, the same held-out cohort in the same norm) for the Stokes cell."""
    d = load(STK)
    s4 = {r["N"]: r for r in d["gates"]["S4"]["rows"]}
    s7 = d["gates"]["S7"]["rows"]

    ex, ac = [], []
    for r in s7:
        n = r["N"]
        g = s4[n]
        ex.append(f"    {n} & {g['resid_canc_max']:.1e} & {g['jac_canc_max']:.1e} & "
                  f"{r['press_elim_fom_pressure']:.1e} & {r['rank_A']} & "
                  f"{r['cond_A']:.1f} \\\\")
        e = r["err"]
        t = r["times"]
        ac.append(f"    {n} & {e['nl_qf']['agg']:.3e} & {e['podK']['agg']:.3e} & "
                  f"{e['podK']['agg']/e['nl_qf']['agg']:.2f}$\\times$ & "
                  f"\\textbf{{{e['gspan_direct']['agg']:.2e}}} & "
                  f"{e['podR_galerkin']['agg']:.2e} & "
                  f"{e['nl_qf']['agg']/e['gspan_direct']['agg']:.1e} & "
                  f"{t['rom_qf_nonlinear']['median']/t['rom_gspan_direct']['median']:.0f}$\\times$ \\\\")

    nh = s7[0]["n_heldout"]
    kl = d["config"]["k_lat"]
    rm = d["config"]["r_main"]
    tex = f"""{{\\footnotesize\\textbf{{Exactness}} --- gates S4 (against an
  \\emph{{independent}} strong-form full-grid path) and the S7 pressure rung}}\\par\\vspace{{1mm}}
\\begin{{tabular}}{{@{{}}rrrrrr@{{}}}}
  \\toprule
  $N$ & residual & Jacobian & pressure elim.\\ vs FOM $p$ & rank $A$ & cond $A$\\\\
  \\midrule
{chr(10).join(ex)}
  \\bottomrule
\\end{{tabular}}
\\vspace{{2mm}}

{{\\footnotesize\\textbf{{Accuracy}} --- {nh} held-out parameters, one
  mass-weighted centred norm, $K={kl}$, $R={rm}$}}\\par\\vspace{{1mm}}
\\begin{{tabular}}{{@{{}}rrrrrrrr@{{}}}}
  \\toprule
  $N$ & nonlinear QF ROM & POD-{kl} & vs POD-{kl} & \\textbf{{direct $G$-span}} & POD-{rm} Galerkin
  & QF\\,/\\,$G$-span err & QF\\,/\\,$G$-span time\\\\
  \\midrule
{chr(10).join(ac)}
  \\bottomrule
\\end{{tabular}}"""
    w("cross-pde-stokes-results.tex", tex)


# ------------------------------------------------------------------- Poisson
def poisson():
    runs = {}
    for p in sorted(glob.glob(os.path.join(PQF, "qf_n*", "out",
                                           "sep_poisson_qf_*.json"))):
        d = load(p)
        assert d["complete"], f"incomplete: {p}"
        runs[d["config"]["N"]] = d
    runs = dict(sorted(runs.items()))

    rows = []
    gpus = set()
    for n, d in runs.items():
        gpus.add(gpu_short(d["config"]["gpu"]))
        by = {}
        for row in d["rows"]:
            if row["cohort"].startswith("held") and row["tau"] == 1e-3:
                by[row["method"]] = row
        su = d["setup"]
        rows.append(
            f"    {n} & {by['full']['m']:,} & {by['full']['time_ms']:.2f} & "
            f"{by['eq']['m']} & {by['eq']['time_ms']:.2f} & "
            f"\\textbf{{{by['qf']['m']}}} & "
            f"\\textbf{{{by['qf']['time_ms']:.2f}}} & "
            f"{su['eq_nnls_fit_s'] + su['eq_bank_and_table_s']:.1f} & "
            f"\\textbf{{{su['qf_b_matmul_s']:.1f}}} \\\\".replace(",", "\\,"))

    tex = f"""\\begin{{tabular}}{{@{{}}rrrrrrrrr@{{}}}}
  \\toprule
  & \\multicolumn{{2}}{{c}}{{full grid}} & \\multicolumn{{2}}{{c}}{{sampled (NNLS)}}
  & \\multicolumn{{2}}{{c}}{{\\textbf{{quadrature-free}}}} & \\multicolumn{{2}}{{c}}{{setup s}}\\\\
  \\cmidrule(lr){{2-3}}\\cmidrule(lr){{4-5}}\\cmidrule(lr){{6-7}}\\cmidrule(lr){{8-9}}
  $N$ & pts & ms & pts & ms & pts & ms & NNLS & \\textbf{{QF}}\\\\
  \\midrule
{chr(10).join(rows)}
  \\bottomrule
\\end{{tabular}}

\\vspace{{1.5mm}}
{{\\footnotesize Online solve ms per held-out source at $\\tau=10^{{-3}}$; all
three paths through the identical solver, {', '.join(sorted(gpus))}.}}"""
    w("cross-pde-cost-poisson.tex", tex)


# ------------------------------------------------- coverage / not-measured
def heat_ratio():
    """The Heat direct-POD-Galerkin-vs-FOM speed ratio exists ONLY as prose in
    a generated report; there is no per-N cost JSON for Heat anywhere in this
    project.  Parse it -- do not retype it."""
    txt = open(HEAT_REPORT).read()
    m = re.search(r"\*\*(\d+)[–-](\d+)× faster than the FOM\*\*", txt)
    assert m, "Heat aggregate ratio not found in " + HEAT_REPORT
    return m.group(1), m.group(2)


def coverage():
    lo, hi = heat_ratio()
    tex = f"""\\begin{{tabular}}{{@{{}}llll@{{}}}}
  \\toprule
  PDE class & residual degree & per-$N$ online-cost ladder & crossover vs the FOM\\\\
  \\midrule
  Poisson 2D & 1 (linear) & measured, $N=128/256/512$ & not measured (soft: vs unpreconditioned CG)\\\\
  Heat 2D/3D & 1 (linear) & {NM} & {NM}; only an aggregate:\\\\
   & & \\multicolumn{{2}}{{l}}{{\\quad direct reduced POD--Galerkin
       ${lo}$--${hi}\\times$ faster than the FOM (no $N$ ladder behind it)}}\\\\
  Wave 2D & 1 (linear, conservative) & {NM} & {NM} --- cell retired unimplemented\\\\
  Burgers 1D & 2 (quadratic) & measured, $N=128\\ldots65\\,536$ & no crossover: launch-bound below $\\sim10^{{4}}$ pts\\\\
  Burgers 2D & 2 (quadratic) & measured, $N=64/256/512/1024$ & $\\approx N=512$ (tensor flat, oracle $O(n)$)\\\\
  Stokes 2D & 1 (linear, vector, constrained) & measured, $N=32/64/128/256$ & $N=128$ (QF ROM under the FOM back-solve)\\\\
  Navier--Stokes & 2 (quadratic) & not run yet & not run yet\\\\
  \\bottomrule
\\end{{tabular}}"""
    w("cross-pde-cost-coverage.tex", tex)


if __name__ == "__main__":
    burgers_1d()
    burgers_2d()
    stokes()
    stokes_results()
    poisson()
    coverage()
