#!/usr/bin/env python
"""Generate the tables for reports/2026-08-25-poisson-architecture-and-results.md

Poisson-only view. Reads committed run JSONs across the scaling-arm worktrees and
the N=256 push worktree. Never hand-type a number into the report.

    /home/tahmid/Dev/.venv/bin/python reports/gen_2026-08-25-poisson-summary.py

NOTE: every worktree carries the inherited N=64 `sepdec_r1/` archive, so a loose
glob can match the WRONG mesh. load_at() asserts each file's own config N.
"""
import glob
import json
import os

WT = "/home/tahmid/Dev/pod-ae-nmrom/Tunable-NM-ROM-Claude/worktrees"
PUSH = f"{WT}/2026-08-23-n256-push/experiments/separable-decoder"
ARM = {n: f"{WT}/2026-08-23-sepdec-n{n}/experiments/separable-decoder"
       for n in (128, 256, 512, 1024)}
R1 = f"{WT}/2026-08-22-separable-decoder/experiments/separable-decoder"


def g(d, *keys, default=float("nan")):
    for k in keys:
        if isinstance(d, dict) and d.get(k) is not None:
            return d[k]
    return default


def load_at(pats, N, k=None):
    for pat in pats:
        for p in sorted(glob.glob(pat)):
            try:
                c = json.load(open(p)).get("config", {})
            except Exception:
                continue
            if int(g(c, "N", default=-1)) != int(N):
                continue
            if k is not None and int(g(c, "k", default=-1)) != int(k):
                continue
            return p, json.load(open(p))
    return None, None


def rows(d):
    return [r for r in d.get("rows", []) if isinstance(r, dict)]


print("<!-- GENERATED by reports/gen_2026-08-25-poisson-summary.py "
      "-- do not hand-edit -->")

# ---------------------------------------------------------------- P1 scaling
print("\n### P1. Solve cost vs grid size (K=16, held-out sources, tau=1e-3)\n")
print("| grid N | unknowns | ROM ms | ROM error | classical CG ms | CG error | who wins |")
print("|---|---|---|---|---|---|---|")
SRC = [
    (64, [f"{R1}/runs/sepdec_r1/out/sep_poisson_K16_R64.json"]),
    (128, [f"{ARM[128]}/runs/*/out/sep_poisson_K16_*.json"]),
    (256, [f"{ARM[256]}/runs/n256_j4/out/sep_poisson_K16_R64_s200k.json",
           f"{ARM[256]}/runs/*/out/sep_poisson_K16_*.json"]),
    (512, [f"{ARM[512]}/runs/*/out/sep_poisson_K16_*.json"]),
    (1024, [f"{ARM[1024]}/runs/*/out/sep_poisson_N1024_K16_*.json"]),
]
spectral = []
for N, pats in SRC:
    p, d = load_at(pats, N, k=16)
    if d is None:
        print(f"| {N} | | NOT FOUND | | | | |")
        continue
    sep = [r for r in rows(d)
           if "cach" in str(g(r, "method", "arm", default=""))
           and float(g(r, "tau", default=-1)) == 1e-3
           and "fresh" not in str(g(r, "cohort", default="held"))]
    fom = list(d.get("fom", [])) or [r for r in rows(d)
                                     if "cg" in str(g(r, "method", default="")).lower()]
    fom = [r for r in fom if "fresh" not in str(g(r, "cohort", default="held"))]
    if not sep or not fom:
        print(f"| {N} | | schema miss | | | | |")
        continue
    s = sep[0]
    st = g(s, "time_ms", "time_ms_median")
    se = g(s, "err_rel_l2", "err_mean")

    def ft(r):
        return g(r, "time_ms", "time_ms_median", default=1e9)

    def fe(r):
        return g(r, "err_rel_l2", "err_rel_l2_mean", default=1e9)

    cg = [r for r in fom if "cg" in str(g(r, "fom", "method", default="cg")).lower()]
    for r in fom:
        if "cg" not in str(g(r, "fom", "method", default="cg")).lower():
            spectral.append((N, g(r, "fom", "method", default="?"), ft(r), fe(r)))
    iso = [r for r in cg if fe(r) <= se]
    pick = min(iso, key=ft) if iso else (min(cg, key=ft) if cg else None)
    if pick is None:
        continue
    ct, ce = ft(pick), fe(pick)
    verdict = f"**ROM {ct/st:.1f}x**" if ct > st else f"CG {st/ct:.1f}x"
    print(f"| {N} | {(N-2)**2:,} | **{st:.2f}** | {se:.2e} | {ct:.2f} | {ce:.1e} | "
          f"{verdict} |")
print("\n*CG column = cheapest tolerance rung at least as accurate as the ROM "
      "(falls back to the cheapest rung if none qualifies). Same job, same GPU.*")
if spectral:
    print("\n**Caveat — a fast direct solver beats both.** Poisson here has constant "
          "coefficients, so an exact spectral solve is available:\n")
    print("| grid N | solver | ms | error |")
    print("|---|---|---|---|")
    for N, name, ms, err in spectral:
        print(f"| {N} | {name} | {ms:.2f} | {err:.1e} |")
    print("\n*The ROM's win is against **iterative** solvers, on problems where no fast "
          "direct method exists. Say it that way.*")

# ---------------------------------------------------------------- P2 accuracy
print("\n### P2. How accurate can the decoder get? (N=256)\n")
print("| run | features | span rank | recon | best fresh-cohort solve |")
print("|---|---|---|---|---|")
for tag, label in (("r2a", "multi-scale"), ("r2b", "single-scale")):
    hits = sorted(glob.glob(f"{PUSH}/runs/push_{tag}_poisson/out/*.json"))
    if not hits:
        continue
    d = json.load(open(hits[0]))
    tr, c = d.get("train", {}), d.get("config", {})
    best = None
    for r in rows(d):
        if "cach" in str(g(r, "method", "arm", default="")) and \
           "fresh" in str(g(r, "cohort", default="")):
            e = g(r, "err_rel_l2", "err_mean")
            if best is None or e < best:
                best = e
    print(f"| {tag} | {label} | R={int(g(c,'r',default=0))} | "
          f"{g(tr,'recon_raw_mean','final_rel_mse'):.3e} | "
          f"{best:.3e} |" if best else "| | | | | |")
print("\n*Single-scale Fourier features beat multi-scale; multi-scale was dropped.*")

# ---------------------------------------------------------------- P3 ceiling
print("\n### P3. The ceiling: how good could the basis ever be? (diagnostic only)\n")
fp = f"{PUSH}/runs/pod_floor/pod_floor_N256_poisson.json"
if os.path.exists(fp):
    blk = json.load(open(fp)).get("poisson", {})
    fam, fresh = blk.get("family_floor", {}), (blk.get("fresh") or {})
    print("| basis size R | best possible error, fresh sources |")
    print("|---|---|")
    for R in sorted(fresh or fam, key=lambda x: int(x)):
        v = fresh.get(R, {})
        val = g(v, "mean") if isinstance(v, dict) else fam.get(R)
        print(f"| {R} | {val:.2e} |")
    print("\n*This is a least-squares fit using the truth, so it is a **diagnostic**, "
          "not something the solver can reach. It says the basis is rich enough; "
          "whether the 16-number recipe can reach into it is a separate question.*")
