#!/usr/bin/env python
"""Generate the data blocks for
reports/2026-08-24-separable-decoder-architecture-and-results.md

Reads ONLY committed run JSONs, across the four scaling-arm worktrees and the
N=256 push worktree. Project rule: never hand-type a number into a report --
run this and paste its output into the GENERATED blocks, or diff to check drift.

    /home/tahmid/Dev/.venv/bin/python reports/gen_2026-08-24_architecture_study.py

NOTE: every worktree carries the inherited N=64 `sepdec_r1/` archive, so any
glob over runs/*/out/ can silently match the WRONG mesh. load_at() asserts the
file's own config N, which is the guard against that.
"""
import glob
import json
import os
import statistics

WT = "/home/tahmid/Dev/pod-ae-nmrom/Tunable-NM-ROM-Claude/worktrees"
PUSH = f"{WT}/2026-08-23-n256-push/experiments/separable-decoder"
ARM = {n: f"{WT}/2026-08-23-sepdec-n{n}/experiments/separable-decoder"
       for n in (128, 256, 512, 1024)}
R1 = f"{WT}/2026-08-22-separable-decoder/experiments/separable-decoder"


def g(d, *keys, default=float("nan")):
    for k in keys:
        if isinstance(d, dict) and d.get(k) is not None:
            return d[k]
    return default


def load_at(pats, N, k=None):
    """First file matching a pattern whose OWN config says N (and k)."""
    for pat in pats:
        for p in sorted(glob.glob(pat)):
            c = json.load(open(p)).get("config", {})
            if int(g(c, "N", default=-1)) != int(N):
                continue
            if k is not None and int(g(c, "k", default=-1)) != int(k):
                continue
            return p, json.load(open(p))
    return None, None


def rows(d):
    return [r for r in d.get("rows", []) if isinstance(r, dict)]


def rel(p):
    return os.path.relpath(p, WT)


print("<!-- GENERATED by reports/gen_2026-08-24_architecture_study.py -- do not hand-edit -->")

# ------------------------------------------------ T1 Poisson scaling
print("\n### T1. Poisson: N-independent ROM cost vs the classical ladder\n")
print("ROM = cached separable arm, K=16, tau=1e-3, held-out cohort. "
      "Baselines are from the SAME job/GPU.\n")
print("| N | ROM ms | ROM err | cheapest CG | cheapest CG at least as accurate | ROM speed-up vs that | other solver in job |")
print("|---|---|---|---|---|---|---|")
SRC_P = [
    (64, [f"{R1}/runs/sepdec_r1/out/sep_poisson_K16_R64.json"]),
    (128, [f"{ARM[128]}/runs/*/out/sep_poisson_K16_*.json"]),
    (256, [f"{ARM[256]}/runs/n256_j4/out/sep_poisson_K16_R64_s200k.json",
           f"{ARM[256]}/runs/*/out/sep_poisson_K16_*.json"]),
    (512, [f"{ARM[512]}/runs/*/out/sep_poisson_K16_*.json"]),
    (1024, [f"{ARM[1024]}/runs/*/out/sep_poisson_N1024_K16_*.json"]),
]
for N, pats in SRC_P:
    p, d = load_at(pats, N, k=16)
    if d is None:
        print(f"| {N} | NOT FOUND | | | | | |")
        continue
    sep = [r for r in rows(d)
           if ("cach" in str(g(r, "method", "arm", default="")))
           and float(g(r, "tau", default=-1)) == 1e-3
           and "fresh" not in str(g(r, "cohort", default="held"))]
    fom = list(d.get("fom", []))
    if not fom:   # some arms store the CG ladder inside rows[] instead
        fom = [r for r in rows(d) if "cg" in str(g(r, "method", default="")).lower()]
    fom = [r for r in fom if "fresh" not in str(g(r, "cohort", default="held"))]
    if not sep or not fom:
        print(f"| {N} | schema miss ({os.path.basename(p)}) | | | | | |")
        continue
    s = sep[0]
    st, se = g(s, "time_ms", "time_ms_median"), g(s, "err_rel_l2", "err_mean")

    def ft(r):
        return g(r, "time_ms", "time_ms_median", default=1e9)

    def fe(r):
        return g(r, "err_rel_l2", "err_rel_l2_mean", default=1e9)

    def kind(r):
        return str(g(r, "fom", "method", default="cg")).lower()
    cg = [r for r in fom if "cg" in kind(r)]
    oth = [r for r in fom if "cg" not in kind(r)]
    cheap = min(cg, key=ft) if cg else None
    iso = [r for r in cg if fe(r) <= se]
    isob = min(iso, key=ft) if iso else None
    cs = f"{ft(cheap):.2f} ms @ {fe(cheap):.1e}" if cheap else "--"
    iss = f"{ft(isob):.2f} ms @ {fe(isob):.1e}" if isob else "none"
    rt = f"**{ft(isob)/st:.2f}x**" if isob else "--"
    os_ = "; ".join(f"{g(r,'fom',default='?')} {ft(r):.2f} ms @ {fe(r):.1e}" for r in oth) or "--"
    print(f"| {N} | {st:.2f} | {se:.3e} | {cs} | {iss} | {rt} | {os_} |")
    print(f"|   | | | | | | <sub>{rel(p)}</sub> |")

# ------------------------------------------------ T2 Burgers scaling
print("\n### T2. Burgers: end-to-end ROM vs the strong classical baseline\n")
print("ROM e2e = IC latent fit + 50 implicit steps + full-grid decode, one job, one GPU.\n")
print("| N | ROM e2e ms | ROM err | cheapest Newton at least as accurate | truth-gen (over-solved) | verdict |")
print("|---|---|---|---|---|---|")
SRC_B = [
    (128, [f"{ARM[128]}/runs/*/out/sep_burgers_K16_*.json"]),
    (256, [f"{ARM[256]}/runs/*/out/sep_burgers_K16_*.json"]),
    (512, [f"{ARM[512]}/runs/*/out/sep_burgers_K16_*.json"]),
    (1024, [f"{ARM[1024]}/runs/*/out/sep_burgers_N1024_K16_*.json"]),
]
for N, pats in SRC_B:
    p, d = load_at(pats, N, k=16)
    if d is None:
        print(f"| {N} | NOT FOUND | | | | |")
        continue
    rr = rows(d)
    sep = [r for r in rr if "cach" in str(g(r, "method", "arm", default=""))]
    if not sep:
        print(f"| {N} | schema miss | | | | |")
        continue
    s = min(sep, key=lambda r: g(r, "e2e_ms_median", "rollout_only_ms_median",
                                 "time_ms_median", default=1e9))
    st = g(s, "e2e_ms_median", "rollout_only_ms_median", "time_ms_median")
    summ0 = (d.get("timing") or {}).get("summary") or {}
    if st != st and "rom_cached_e2e" in summ0:
        st = summ0["rom_cached_e2e"]["median_ms"]
    se = g(s, "err_traj_rel_mean")
    # baseline rows live in rows[] (n128/n256) OR under top-level keys
    # fom_newton_tol + timing.summary (n512) OR fom_tolnewton (n1024).
    nt = [r for r in rr if "newton_tol" in str(g(r, "method", default=""))]
    tg = [r for r in rr if "truthgen" in str(g(r, "method", default=""))
          or "fixed8" in str(g(r, "method", default=""))]
    if not nt:
        alt = d.get("fom_tolnewton") or d.get("fom_newton_tol") or []
        summ = (d.get("timing") or {}).get("summary") or {}
        for r in alt:
            r = dict(r)
            if "time_ms_median" not in r:      # n512: times live in timing.summary
                key = next((k for k in summ if k.startswith("fom_newton")
                            and f"{g(r,'ntol',default=-1):g}" in k), None)
                if key:
                    r["time_ms_median"] = summ[key]["median_ms"]
            if "time_ms_median" in r:
                r["method"] = "fom_newton_tol"
                nt.append(r)
        if not tg and isinstance(d.get("fom_truth"), dict):
            tg = [{"method": "fom_truth", "time_ms_median": d["fom_truth"]["time_ms_median"]}]
        if not tg and "fom_truth_newton8" in summ:
            tg = [{"method": "fom_truth", "time_ms_median": summ["fom_truth_newton8"]["median_ms"]}]

    def nft(r):
        return g(r, "e2e_ms_median", "time_ms_median", default=1e9)

    iso = [r for r in nt if g(r, "err_traj_rel_mean", default=1e9) <= se]
    if iso:
        b = min(iso, key=nft)
        bs = f"{nft(b):.1f} ms @ {g(b,'err_traj_rel_mean'):.1e}"
        verdict = f"classical wins ({st/nft(b):.1f}x slower)" if nft(b) < st else f"**ROM wins {nft(b)/st:.1f}x**"
    else:
        bs = "none in job" if nt else "no strong baseline in job"
        verdict = "incomparable"
    tgs = f"{nft(tg[0]):.0f} ms" if tg else "--"
    print(f"| {N} | {st:.1f} | {se:.3e} | {bs} | {tgs} | {verdict} |")
    print(f"|   | | | | | <sub>{rel(p)}</sub> |")

# ------------------------------------------------ T3 push round 2 Burgers
print("\n### T3. N=256 push, round 2 (Burgers primary): the error ladder\n")
p = f"{PUSH}/runs/push_r2_burgers/out/sep_burgers_r2_K16_R512.json"
d = json.load(open(p))
cfg, tr = d["config"], d["train"]
print(f"Source: `{rel(p)}` - K={cfg.get('k')}, R_nominal={cfg.get('r')}, "
      f"{tr.get('steps_done')} steps, {cfg.get('max_snaps')} states, "
      f"ff_scales={cfg.get('ff_scales', cfg.get('ff_scale', 'n/a'))}\n")
for gk, gv in (d.get("gates") or {}).items():
    print(f"- equivalence gate `{gk}`: **{gv:.2e}**")
print(f"- IC path jit-vs-incumbent deviation: **{g(d.get('ic',{}),'jit_vs_incumbent_rel_dev'):.2e}** "
      f"({g(d.get('ic',{}),'n_candidates',default='?')} candidates)")
print(f"- **reconstruction** (training states): **{g(tr,'recon_raw_mean','final_rel_mse'):.3e}**")
orc = d.get("oracle", [])
if isinstance(orc, list) and orc:
    mm = [o["mean"] for o in orc if "mean" in o]
    t0 = [o["t0"] for o in orc if "t0" in o]
    print(f"- **per-state oracle**, {len(mm)} fresh trajectories: mean "
          f"**{statistics.mean(mm):.3e}**, worst trajectory {max(mm):.3e}; "
          f"t0/IC floor {statistics.mean(t0):.3e}")
for setname, lst in (d.get("single_step_weak_opt") or {}).items():
    rat = [e["err"] / e["oracle_err"] for e in lst if e.get("oracle_err")]
    if rat:
        print(f"- **single-step weak-opt / oracle** [{setname}]: mean "
              f"**{sum(rat)/len(rat):.4f}**, max {max(rat):.4f} ({len(rat)} probes)")
print("\n| arm | EQ set | IC | rollout | e2e ms | traj err mean | traj err max | jacs |")
print("|---|---|---|---|---|---|---|---|")
seen = set()
for r in rows(d):
    if "cach" not in str(g(r, "method", "arm", default="")):
        continue
    key = (g(r, 'eq_set', default='-'), g(r, 'ic', default='-'), g(r, 'roll', default='-'))
    if key in seen:
        continue
    seen.add(key)
    print(f"| cached | {key[0]} | {key[1]} | {key[2]} | {g(r,'e2e_ms_median'):.1f} | "
          f"{g(r,'err_traj_rel_mean'):.3e} | {g(r,'err_traj_rel_max'):.3e} | "
          f"{g(r,'jac_total_mean',default=float('nan')):.0f} |")
print("\nSame-job classical baselines:\n")
print("| solver | tol | ms | err |")
print("|---|---|---|---|")
for r in rows(d):
    m = str(g(r, "method", default=""))
    if "newton" in m:
        print(f"| {m} | {g(r,'newton_tol',default='-')} | "
              f"{g(r,'e2e_ms_median','time_ms_median'):.1f} | {g(r,'err_traj_rel_mean'):.3e} |")

# ------------------------------------------------ T4 Poisson control
print("\n### T4. N=256 push, round 2 Poisson control\n")
print("| run | Fourier features | recon | best fresh-cohort solve | at ms |")
print("|---|---|---|---|---|")
for tag, label in (("r2a", "multi-scale (1,4,16)"), ("r2b", "single-scale")):
    hits = sorted(glob.glob(f"{PUSH}/runs/push_{tag}_poisson/out/*.json"))
    if not hits:
        continue
    d2 = json.load(open(hits[0]))
    tr2 = d2.get("train", {})
    best = None
    for r in rows(d2):
        if "cach" in str(g(r, "method", "arm", default="")) and "fresh" in str(g(r, "cohort", default="")):
            e = g(r, "err_rel_l2", "err_mean")
            if best is None or e < best[0]:
                best = (e, g(r, "time_ms", "time_ms_median"))
    bs = f"{best[0]:.3e} | {best[1]:.2f} |" if best else "-- | -- |"
    print(f"| {tag} | {label} | {g(tr2,'recon_raw_mean','final_rel_mse'):.3e} | {bs}")

# ------------------------------------------------ T5 POD floors
print("\n### T5. POD floors -- DIAGNOSTIC ONLY (no POD enters any model)\n")
print("Best possible accuracy for ANY architecture whose online field is a fixed "
      "spatial bank times latent coefficients, i.e. the separable family's hard ceiling.\n")
for pde in ("burgers", "poisson"):
    fp = f"{PUSH}/runs/pod_floor/pod_floor_N256_{pde}.json"
    if not os.path.exists(fp):
        continue
    fd = json.load(open(fp))
    blk = fd.get(pde, {})
    print(f"\n**{pde}** - `{rel(fp)}`\n")
    print("| rank R | family floor | fresh cohort (mean) | (max) |")
    print("|---|---|---|---|")
    fam = blk.get("family_floor", {})
    ts = blk.get("test_states") or blk.get("fresh") or {}
    dense = blk.get("dense", {})
    if dense:
        print(f"| <sub>(dense {dense.get('n_snapshots','?')}-sample family also computed; see JSON)</sub> | | | |")
    for R in sorted(set(list(fam) + list(ts)), key=lambda x: int(x)):
        f1 = fam.get(R)
        t = ts.get(R, {})
        print(f"| {R} | {f1:.2e} | {g(t,'mean'):.2e} | {g(t,'max'):.2e} |"
              if f1 is not None else
              f"| {R} | -- | {g(t,'mean'):.2e} | {g(t,'max'):.2e} |")

print("\n### T6. Feature-bank rank spectrum\n")
print(f"Source: `{rel(PUSH)}/runs/rank_check/rank_check_N256.log` (committed).\n")
rc = f"{PUSH}/runs/rank_check/rank_check_N256.log"
if os.path.exists(rc):
    for line in open(rc):
        if line.strip():
            print(f"    {line.rstrip()}")

# ------------------------------------------------ T7 nonlinear vs linear
print("\n### T7. What the nonlinearity buys: K nonlinear coefficients vs R linear modes\n")
fp = f"{PUSH}/runs/pod_floor/pod_floor_N256_burgers.json"
rp = f"{PUSH}/runs/push_r2_burgers/out/sep_burgers_r2_K16_R512.json"
if os.path.exists(fp) and os.path.exists(rp):
    import numpy as np
    sv = np.asarray(json.load(open(fp))["burgers"]["svals"], dtype=float)
    en = sv ** 2
    tot = en.sum()

    def pod_floor(R):
        return float(np.sqrt(max(en[R:].sum(), 0.0) / tot))

    rd = json.load(open(rp))
    K = int(rd["config"]["k"])
    recon = float(g(rd["train"], "recon_raw_mean", "final_rel_mse"))
    eq = [R for R in range(1, len(sv)) if pod_floor(R) <= recon]
    print(f"- trained **K={K}** separable decoder, reconstruction **{recon:.3e}** "
          f"(`{rel(rp)}`)")
    print(f"- linear **POD rank {K}** floor on the same family: **{pod_floor(K):.3e}** "
          f"({pod_floor(K)/recon:.1f}x worse)")
    print(f"- smallest linear POD rank matching that reconstruction: **{eq[0] if eq else 'n/a'}**")
    print(f"\n  => {K} nonlinear coefficients are worth about **{eq[0] if eq else '?'} "
          f"linear basis functions** on this family.")

# ------------------------------------------------ T8 round-5 accuracy campaign
print("\n### T8. Round-5 Burgers accuracy campaign (N=256): what the h-generalisation "
      "work bought\n")
print("Every row is one *speed* job run on a frozen decoder checkpoint, so error and cost "
      "come from the same protocol as T2/PROFILE (end-to-end incl. IC fit and full decode, "
      "matched-accuracy paired AB/BA against a swept (newton_tol, lin_tol) "
      "Helmholtz-preconditioned classical ladder). `paired` > 1 means the ROM is faster.\n")
print("> **These rows are ALL N=256, where the classical solver wins regardless of decoder "
      "quality (0.39x for the incumbent).** Do not read the sub-1 ratios as a regression "
      "against the round-4 speed result: that win was at **N=1024** (1.61x single-query, "
      "T2/PROFILE), the only resolution where the ROM leads. The accuracy campaign ran at "
      "N=256 because iteration is ~1.5 h there versus 4 h+, and the h gap is "
      "resolution-independent (36.8x at N=256 vs 31.7x at N=1024), so its findings "
      "transfer. The N=1024 confirmation had not run when this was generated.\n>\n"
      "> **Projection to N=1024, explicitly not a measurement:** the improved decoder "
      "costs 1.27x more, and the classical rung it must now match also costs 1.32x more "
      "(13.81 -> 18.26 ms, since a more accurate ROM must be compared against a more "
      "accurate classical setting). Both sides rise together -- which is why the N=256 "
      "ratio held at 0.39x -> 0.40x. Applying the same scaling at N=1024 gives ROM "
      "~34 ms against classical ~57 ms, i.e. the 1.61x roughly preserved at 3x better "
      "accuracy. That is what the queued `dn1024` job settles.\n")
ACC = f"{WT}/2026-08-25-burgers-accuracy/experiments/separable-decoder/runs"
NPUSH = f"{WT}/2026-08-23-n256-push/experiments/separable-decoder/runs"
speed = []
for pat, tag in ((f"{NPUSH}/push_r4s256a/out/sep_speed_r4_*.json", "round-4 incumbent"),
                 (f"{ACC}/*/out/sep_speed_r5_*.json", None)):
    for fp in sorted(glob.glob(pat)):
        try:
            dd = json.load(open(fp))
        except Exception:
            continue
        if int(g(dd.get("config", {}), "N", default=-1)) != 256:
            continue
        speed.append((tag or os.path.basename(g(dd["config"], "ckpt", default="?"))
                      .replace("sep_hfit_", "").replace(".pkl", ""), fp, dd))
if not speed:
    print("_(no round-5 speed JSONs found)_")
else:
    print("| decoder | K | EQ | rollout err | ROM e2e ms | matched classical (ms @ err) "
          "| paired | EQ-bank gate |")
    print("|---|---|---|---|---|---|---|---|")
    rows_out = []
    for label, fp, dd in speed:
        c = dd["config"]
        ma = dd.get("matched_accuracy") or {}
        m = ma.get("matched") or {}
        pr = ma.get("paired") or {}
        eqset = "M=256" if "M256" in os.path.basename(fp) else "M=64"
        rom_ms = g(ma, "rom_e2e_ms")
        err = g(ma, "rom_err")
        ratio = (pr.get("base_ms") / pr.get("rom_ms")) if pr.get("rom_ms") else float("nan")
        gate = g(dd.get("gates", {}), "eq_bank_vs_meshfree")
        rows_out.append((err, label, int(g(c, "k", default=0)), eqset, err, rom_ms,
                         g(m, "ms"), g(m, "err"), ratio, gate))
    for _, label, k, eqset, err, rom_ms, cms, cerr, ratio, gate in sorted(rows_out,
                                                                         reverse=True):
        print(f"| {label} | {k} | {eqset} | **{err:.3e}** | {rom_ms:.2f} | "
              f"{cms:.2f} @ {cerr:.1e} | {ratio:.2f}x | {gate:.1e} |")
    best = min(rows_out)
    inc = [r for r in rows_out if r[1] == "round-4 incumbent"]
    if inc:
        i = inc[0]
        # the Pareto move: best error among arms whose paired ratio is no worse
        # than the incumbent's -- i.e. accuracy bought without losing ground to
        # the classical ladder.
        held = [r for r in rows_out if r[1] != "round-4 incumbent" and r[8] >= i[8]]
        if held:
            b = min(held)
            print(f"\n=> **At an unchanged position against the classical ladder** "
                  f"({i[8]:.2f}x -> {b[8]:.2f}x), rollout error improves "
                  f"**{i[4]:.3e} -> {b[4]:.3e} = {i[4]/b[4]:.2f}x** (`{b[1]}`). The ROM "
                  f"costs {b[5]/i[5]:.2f}x more, and so does the classical rung it must "
                  f"now match -- a Pareto move, not a trade.")
        print(f"\n=> **Best error of the campaign**: **{best[4]:.3e}** (`{best[1]}`, "
              f"{i[4]/best[4]:.2f}x better than the incumbent), but at {best[8]:.2f}x "
              f"vs the incumbent's {i[8]:.2f}x -- i.e. {i[8]/best[8]:.1f}x of the "
              f"speed ratio spent to buy it.")
    print("\nFull campaign (35 h-arms, the K and mu-density ladders, and the levers that "
          "failed) is in `reports/2026-08-25-burgers-h-generalisation-wall.md` on branch "
          "`exp/2026-08-25-burgers-accuracy`.")
