"""Provenance manifest for the 2026-09-16 tunability-campaign handoff.

Walks every lane cited by the handoff, records the branch head, whether the worktree is
clean, and the SHA256 of each generated report, and writes the manifest Markdown + JSON
beside the handoff. Re-run it to check that nothing cited has drifted:

    /home/tahmid/Dev/.venv/bin/python reports/generate_handoff_manifest.py
"""
import hashlib
import json
import subprocess
from pathlib import Path

ROOT = Path('/home/tahmid/Dev/pod-ae-nmrom/Tunable-NM-ROM-Claude')
OUT_MD = ROOT / 'reports/2026-09-16-tunability-campaign-handoff.manifest.md'
OUT_JSON = ROOT / 'reports/2026-09-16-tunability-campaign-handoff.manifest.json'

LANES = [
    ('head ablation (E3) + correction ladder', '2026-09-14-head-ablation',
     ['experiments/head-ablation/reports/2026-09-14-head-ablation.md',
      'experiments/head-ablation/reports/2026-09-14-burgers-correction-ladder.md',
      'experiments/head-ablation/checks/zero-start/poisson_zero_start.json',
      'experiments/head-ablation/checks/cold-start-caps/poisson_cap_curve.json',
      'experiments/head-ablation/checks/cold-start-caps/burgers_cap_curve.json']),
    ('fixed-checkpoint tuning (E5)', '2026-09-14-no-burgers',
     ['experiments/neural-operator-burgers/reports/2026-09-14-fixed-checkpoint-tuning.md']),
    ('Burgers FNO baseline (E6)', '2026-09-14-no-audit',
     ['experiments/neural-operator-audit/reports/2026-09-14-burgers-fno-baseline.md']),
    ('prior dial', '2026-09-15-prior-dial',
     ['experiments/prior-dial/reports/2026-09-15-prior-dial.md']),
    ('head refinement', '2026-09-15-head-refine',
     ['experiments/head-refine/reports/2026-09-15-per-query-head-refinement.md']),
    ('cheap corrections', '2026-09-15-cheap-corrections',
     ['experiments/cheap-corrections/reports/2026-09-15-cheap-corrections.md']),
    ('Burgers ladder top + envelope', '2026-09-16-b-ladder-top',
     ['experiments/b-ladder-top/reports/2026-09-16-b-ladder-top.md']),
    ('Burgers speed', '2026-09-16-b-speed',
     ['experiments/b-speed/reports/2026-09-16-b-speed.md']),
    ('Burgers head training', '2026-09-16-b-head-train',
     ['reports/2026-09-16-can-training-move-the-burgers-head.md']),
    ('Poisson bank and head', '2026-09-16-p-bank-head',
     ['experiments/p-bank-head/reports/2026-09-16-poisson-bank-and-head.md']),
    ('paper refresh + mirror plan', '2026-09-16-paper-refresh',
     ['paper/OUTLINE.md', 'paper/REVIEWER-RESPONSE-MAP.md',
      'reports/2026-09-16-code-only-github-mirror-plan.md',
      'paper/figures/gen_fig_tunability_family.py']),
    ('q=16 diagnosis', '2026-09-16-q-diag',
     ['experiments/q-diag/reports/2026-09-16-q16-regression-diagnosis.md']),
    ('dense ladder certification', '2026-09-16-q-trajdirs',
     ['experiments/q-trajdirs/reports/2026-09-16-dense-correction-ladder.md']),
    ('EQ rule certification (in progress at handoff)', '2026-09-16-q-ridge',
     ['experiments/q-ridge/reports/2026-09-16-q-ridge.md']),
]


def git(wt, *args):
    return subprocess.run(['git', '-C', str(wt), *args], capture_output=True, text=True).stdout.strip()


def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def main():
    rows, data = [], []
    for label, wt, files in LANES:
        w = ROOT / 'worktrees' / wt
        head = git(w, 'rev-parse', '--short', 'HEAD') if w.exists() else 'missing'
        branch = git(w, 'rev-parse', '--abbrev-ref', 'HEAD') if w.exists() else '—'
        dirty = len(git(w, 'status', '--short').splitlines()) if w.exists() else -1
        for f in files:
            p = w / f
            present = p.exists()
            h = sha(p) if present else None
            rows.append((label, branch, head, 'clean' if dirty == 0 else f'{dirty} modified', f, h[:16] + '…' if h else 'not found'))
            data.append(dict(lane=label, worktree=wt, branch=branch, head=head, uncommitted=dirty, file=f,
                             present=present, sha256=h))
    lab = ROOT / 'LAB-LOG.md'
    lab_sha = sha(lab)
    lines = ['# Provenance manifest — 2026-09-16 tunability-campaign handoff', '',
             'Generated by `reports/generate_handoff_manifest.py`; every hash below is computed from the file on disk at generation time. '
             'Re-run the script and diff this file to detect drift. Branch heads are local only (nothing from 2026-09-1x is on GitHub).', '',
             f'`LAB-LOG.md` SHA256 at generation: `{lab_sha}` (modified-uncommitted on `main` by standing instruction).', '',
             '| lane | branch | head | worktree | file | SHA256 (prefix) |', '|---|---|---|---|---|---|']
    for r in rows:
        lines.append('| ' + ' | '.join(f'`{x}`' if i in (1, 2, 4) else str(x) for i, x in enumerate(r)) + ' |')
    OUT_MD.write_text('\n'.join(lines) + '\n')
    OUT_JSON.write_text(json.dumps(dict(lab_log_sha256=lab_sha, entries=data), indent=1) + '\n')
    missing = [d for d in data if not d['present']]
    print(f'wrote {OUT_MD.name}: {len(data)} files, {len(missing)} not found')
    for d in missing:
        print('  not found:', d['worktree'], d['file'])


if __name__ == '__main__':
    main()
