"""Appendix training/solver configuration table and paragraph, rendered from the hash-pinned transcription
evidence/training-configs-2026-09-21/transcription.json (values transcribed from committed configuration and
code blobs in the lane worktrees; the blob SHA256s are recorded there).  Normal builds never read a worktree."""
import json
from pathlib import Path
HERE = Path(__file__).resolve().parent
T = json.loads((HERE / 'evidence/training-configs-2026-09-21/transcription.json').read_text())
for r in T['rows']:
    assert r['src'] and all(k in T['sources'] and len(T['sources'][k]['sha256']) == 64 for k in r['src'])
lines = [r'% GENERATED by paper/gen_training_appendix.py from evidence/training-configs-2026-09-21 -- do not edit.', r'\scriptsize',
         r'\begin{tabular}{@{}llp{3.2cm}p{3.4cm}p{2.2cm}p{2.0cm}p{2.4cm}@{}}', r'\toprule',
         r'Model & Stage & Network & Optimiser, learning rate & Steps & Batch & Training data \\', r'\midrule']
for r in T['rows']:
    lines.append(' & '.join([r['model'].replace('Heat 3D (', 'Heat 3D, earlier bank ('), r['stage'], r['net'], r['opt'], r['steps'], r['batch'], r['data']]) + r' \\')
lines += [r'\bottomrule', r'\end{tabular}']
(HERE / 'tables/TH_training_all.tex').write_text('\n'.join(lines) + '\n')
hd = ['Model', 'Stage', 'Network', 'Optimiser, learning rate', 'Steps', 'Batch', 'Training data']
(HERE / 'tables-md/TH_training_all.md').write_text('| ' + ' | '.join(hd) + ' |\n|' + ' --- |' * len(hd) + '\n'
    + ''.join('| ' + ' | '.join(r[k].replace('$', '') for k in ('model', 'stage', 'net', 'opt', 'steps', 'batch', 'data')) + ' |\n' for r in T['rows']))
(HERE / 'tables/TH_solver_details.tex').write_text('% GENERATED by paper/gen_training_appendix.py -- do not edit.\n'
    + r'\paragraph{Full-order and solver details.} ' + T['text']['newton'] + ' ' + T['text']['lshape'] + ' ' + T['text']['pred2'] + '\n')
print(f"training appendix: {len(T['rows'])} rows from {len(T['sources'])} pinned blobs")
