#!/usr/bin/env python3
"""Render the manuscript as Markdown (paper/PAPER.md) from the LaTeX sources.

- Every prose number is expanded from tables/numbers.tex (itself generated by
  gen_tables.py); nothing is typed here.
- Each \\input{tables/Tnn_*} becomes an HTML comment naming the table id
  followed by the generated GitHub-flavoured table from tables-md/, so the
  table can be regenerated in place.
- Pending placeholders (\\gen{...}) become **[PENDING: ...]**.
- Section headings are numbered exactly as the LaTeX numbers them; appendices
  are lettered.  Every section starts with an HTML comment naming the lane
  summary files its numbers came from.

Usage:  /home/tahmid/Dev/.venv/bin/python paper/gen_paper_md.py
"""
from __future__ import annotations

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / 'PAPER.md'

SECTION_SOURCES = {
    'Introduction': ['b-qxm analysis.json', 'b-eqtop summary.json', 'mesh-ladder json', 'b-panel summary.json'],
    'Related work and what is new here': [],
    'Method': ['b-eqtop summary.json (bars)'],
    'Experimental setup': ['b-panel summary.json', 'tuning02 output-index.json'],
    'Results': ['b-panel summary.json', 'b-qxm analysis.json', 'b-eqtop summary.json + report', 'head-ablation abl01/pabl01-audit.json',
                'b-head-train eval01-audit.json', 'mesh-ladder json', 'b-speed report', 'p-linear summary.json + verdicts.json',
                'heat linear-bank report (2026-09-10)', 'w-ladder summary.json', 'lshape summary.json', 'no-second summary.json'],
    'Limitations': ['no-second summary.json', 'b-eqtop summary.json', 'b-qxm analysis.json'],
    'Conclusion': ['b-qxm analysis.json'],
    'Method details': [],
    'Provenance': ['every lane; tables/provenance.json'],
    'Full tables': ['every lane (see each table comment)'],
    'Reviewer map': [],
    'Glossary': ['b-eqtop summary.json (bars)'],
}

# ----------------------------------------------------------------------- macros
def load_macros():
    M = {}
    for f in ['tables/numbers.tex']:
        for m in re.finditer(r'\\newcommand\{\\([A-Za-z]+)\}\{(.*)\}$', (HERE / f).read_text(), re.M):
            M[m.group(1)] = m.group(2)
    # notation macros (macros.tex) and prose shorthands (main.tex), by hand: they are notation, not numbers
    M.update({
        'Real': r'\mathbb{R}', 'Nat': r'\mathbb{N}', 'Aop': 'A', 'bank': 'G', 'head': r'h_\theta', 'tests': 'P',
        'rowscale': r'\Lambda', 'lift': 'u_{g}', 'bcmask': r'\mu', 'latent': 'z', 'umanifold': 'u', 'dhead': r'Dh_\theta',
        'T': r'^{\top}', 'Tr': r'\operatorname{tr}', 'diag': r'\operatorname{diag}', 'rank': r'\operatorname{rank}',
        'argmin': r'\operatorname*{arg\,min}', 'rfull': 'r', 'rweak': 'r_{w}', 'corr': 'C_q', 'qrank': 'q',
        'evolved': '*evolved*', 'alltimes': '*all-times*', 'sameallo': 'same-allocation',
    })
    return M


ARG = r'\{((?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*)\}'   # one brace group, two levels deep


def expand(s, M):
    # argument macros first
    s = re.sub(r'\\norm' + ARG, r'\\lVert \1 \\rVert', s)
    s = re.sub(r'\\normF' + ARG, r'\\lVert \1 \\rVert_{F}', s)
    s = re.sub(r'\\inner' + ARG + ARG, r'\\langle \1, \2 \\rangle', s)
    s = re.sub(r'\\jac' + ARG, r'J_{\1}', s)
    s = re.sub(r'\\station' + ARG + ARG, r'\\eta(\1,\2)', s)
    s = re.sub(r'\\headc' + ARG, r'h_{\\theta,\1}', s)
    s = re.sub(r'\\rweakn' + ARG, r'r_{w,\1}', s)
    s = re.sub(r'\\gen' + ARG, r'**[PENDING: \1]**', s)
    s = re.sub(r'\\todo' + ARG, r'**[TODO: \1]**', s)
    for _ in range(3):
        s = re.sub(r'\\([A-Za-z]+)(?![A-Za-z])', lambda m: M.get(m.group(1), m.group(0)), s)
    return s


# ----------------------------------------------------------------------- bib
def load_bib():
    B = {}
    txt = (HERE / 'refs.bib').read_text()
    for m in re.finditer(r'@\w+\{([^,]+),(.*?)\n\}', txt, re.S):
        key, body = m.group(1).strip(), m.group(2)
        au = re.search(r'author\s*=\s*\{(.*?)\}\s*,?\s*\n', body, re.S); yr = re.search(r'year\s*=\s*\{?(\d{4})', body)
        names = []
        if au:
            for a in re.split(r'\s+and\s+', au.group(1).replace('\n', ' ')):
                a = a.strip()
                last = a.split(',')[0].strip() if ',' in a else a.split()[-1]
                last = re.sub(r'[{}\\]', '', re.sub(r'\\[a-zA-Z]+', '', last)).replace('~', ' ')
                names.append(last)
        if len(names) > 2:
            who = names[0] + ' et al.'
        elif len(names) == 2:
            who = names[0] + ' & ' + names[1]
        else:
            who = names[0] if names else key
        B[key] = (who, yr.group(1) if yr else '????')
    return B


# ----------------------------------------------------------------------- document
def read_tex(path):
    s = (HERE / path).read_text()
    s = re.sub(r'(?<!\\)%.*', '', s)          # strip comments
    return s


def resolve_inputs(s):
    def rep(m):
        f = m.group(1)
        if f.startswith('tables/'):
            return m.group(0)
        p = HERE / (f if f.endswith('.tex') else f + '.tex')
        return resolve_inputs(re.sub(r'(?<!\\)%.*', '', p.read_text()))
    return re.sub(r'\\input\{([^}]+)\}', rep, s)


def main():
    M = load_macros(); B = load_bib()
    main_tex = read_tex('main.tex')
    body = main_tex[main_tex.index(r'\begin{document}') + len(r'\begin{document}'):main_tex.index(r'\end{document}')]
    body = resolve_inputs(body)
    title = re.search(r'\\title\{(.*?)\}', main_tex).group(1)

    # ---- pass 1: numbering of sections, tables, figures, equations
    labels = {}
    sec = [0, 0]; app = False; tab = 0; fig = 0; eq = 0
    def letter(n): return chr(ord('A') + n - 1)
    pos = 0
    tokens = re.finditer(r'\\appendix|\\section\*?\{([^}]*)\}|\\subsection\{([^}]*)\}|\\begin\{(table|figure|equation)\}|\\label\{([^}]*)\}', body)
    last_num = None
    for t in tokens:
        if t.group(0) == r'\appendix':
            app = True; sec = [0, 0]
        elif t.group(0).startswith(r'\section*'):
            last_num = None
        elif t.group(1) is not None:
            sec[0] += 1; sec[1] = 0; last_num = (letter(sec[0]) if app else str(sec[0]))
        elif t.group(2) is not None:
            sec[1] += 1; last_num = f"{letter(sec[0]) if app else sec[0]}.{sec[1]}"
        elif t.group(3) == 'table':
            tab += 1; last_num = f'Table {tab}'
        elif t.group(3) == 'figure':
            fig += 1; last_num = f'Figure {fig}'
        elif t.group(3) == 'equation':
            eq += 1; last_num = f'({eq})'
        elif t.group(4) is not None:
            labels[t.group(4)] = last_num
    # section labels that follow a subsection label share its number (e.g. sec:method:layers inside 3.5)

    # ---- pass 2: render
    out = [f'# {title}', '', '*Anonymous submission to ICLR 2027. Every number below is generated from run records by `gen_tables.py`; '
           'tables are inlined from `tables-md/` behind an HTML comment naming their id; **[PENDING: …]** marks a lane that has not landed.*', '']
    sec = [0, 0]; app = False; tab = 0; fig = 0; eq = 0
    i = 0
    text = body
    # normalise whitespace of paragraphs later; work block by block on a token stream
    pattern = re.compile(
        r'\\appendix'
        r'|\\maketitle'
        r'|\\begin\{abstract\}(.*?)\\end\{abstract\}'
        r'|\\section\*\{([^}]*)\}(?:\\label\{[^}]*\})?'
        r'|\\section\{([^}]*)\}\s*\\label\{[^}]*\}'
        r'|\\subsection\{([^}]*)\}\s*\\label\{[^}]*\}'
        r'|\\begin\{table\}(.*?)\\end\{table\}'
        r'|\\begin\{figure\}(.*?)\\end\{figure\}'
        r'|\\begin\{equation\}(.*?)\\end\{equation\}'
        r'|\\begin\{(enumerate|itemize|description)\}(?:\[[^\]]*\])?(.*?)\\end\{\8\}'
        r'|\\begin\{center\}(.*?)\\end\{center\}'
        r'|\\bibliographystyle\{[^}]*\}|\\bibliography\{[^}]*\}|\\clearpage|\\label\{[^}]*\}',
        re.S)

    def inline(s):
        s = expand(s, M)
        s = re.sub(r'\\citep' + ARG, lambda m: '(' + '; '.join(f'{B.get(k.strip(), (k.strip(), "?"))[0]}, {B.get(k.strip(), (k, "?"))[1]}' for k in m.group(1).split(',')) + ')', s)
        s = re.sub(r'\\citet' + ARG, lambda m: '; '.join(f'{B.get(k.strip(), (k.strip(), "?"))[0]} ({B.get(k.strip(), (k, "?"))[1]})' for k in m.group(1).split(',')), s)
        s = re.sub(r'\\S\\ref\{([^}]*)\}', lambda m: '§' + str(labels.get(m.group(1), '?')), s)
        s = re.sub(r'Appendix~\\ref\{([^}]*)\}', lambda m: 'Appendix ' + str(labels.get(m.group(1), '?')), s)
        s = re.sub(r'(Table|Figure|Tables|Figures)~\\ref\{([^}]*)\}', lambda m: str(labels.get(m.group(2), '?')), s)
        s = re.sub(r'\\ref\{([^}]*)\}', lambda m: str(labels.get(m.group(1), '?')), s)
        s = re.sub(r'\\eqref\{([^}]*)\}', lambda m: str(labels.get(m.group(1), '(?)')), s)
        s = re.sub(r'\\textbf' + ARG, r'**\1**', s)
        s = re.sub(r'\\emph' + ARG, r'*\1*', s)
        s = re.sub(r'\\texttt' + ARG, lambda m: '`' + m.group(1).replace('\\_', '_').replace('\\%', '%') + '`', s)
        s = re.sub(r'\\paragraph' + ARG, r'\n\n**\1**', s)
        s = re.sub(r'\\resizebox\{[^}]*\}\{[^}]*\}', '', s)
        s = s.replace('\\ldots', '…').replace('\\%', '%').replace('\\_', '_').replace('\\&', '&').replace('\\#', '#')
        s = s.replace('``', '“').replace("''", '”').replace('---', '—').replace('--', '–').replace('~', ' ')
        s = re.sub(r'\\,', ' ', s); s = re.sub(r'\\;', ' ', s); s = s.replace('\\ ', ' ').replace('\\\\', '  \n')
        s = re.sub(r'\\S(?![a-zA-Z])', '§', s)
        s = re.sub(r'\\label\{[^}]*\}', '', s)
        s = re.sub(r'\$\\(nQ|nP|nE|nA|nM|nT|nW|nL|nO|nH|nC|nS|nN|prov)[A-Za-z]*\$', lambda m: m.group(0), s)  # (macros already expanded)
        s = re.sub(r'[ \t]+', ' ', s)
        s = re.sub(r'\n ', '\n', s)
        return s.strip()

    def math_block(s):
        s = expand(s, M)
        s = re.sub(r'\\label\{[^}]*\}', '', s)
        return '$$\n' + s.strip() + '\n$$'

    def table_block(s):
        nonlocal tab
        tab += 1
        cap = re.search(r'\\caption' + ARG, s, re.S)
        ins = re.findall(r'\\input\{tables/([^}]*)\}', s)
        parts = [f'**Table {tab}.** ' + inline(cap.group(1)) if cap else f'**Table {tab}.**']
        for t in ins:
            md = (HERE / 'tables-md' / (t + '.md')).read_text().splitlines()
            md = [l for l in md if not l.startswith('<!-- GENERATED')]
            parts.append(f'<!-- table: {t} -->\n' + '\n'.join(md))
        return '\n\n'.join(parts)

    def figure_block(s):
        nonlocal fig
        fig += 1
        cap = re.search(r'\\caption' + ARG, s, re.S)
        g = re.search(r'\\includegraphics(?:\[[^\]]*\])?\{([^}]*)\}', s)
        src = f'figures/{g.group(1)}.png' if g else 'figures/architecture.png'
        return f'![Figure {fig}]({src})\n\n**Figure {fig}.** ' + (inline(cap.group(1)) if cap else '')

    def list_block(kind, s):
        items = re.split(r'\\item', s)[1:]
        lines = []
        for n, it in enumerate(items, 1):
            it = it.strip()
            m = re.match(r'\[' + r'((?:[^\[\]]|\[[^\]]*\])*)' + r'\]\s*(.*)', it, re.S)
            if kind == 'description' and m:
                lines.append(f'- **{inline(m.group(1))}** — {inline(m.group(2))}')
            elif kind == 'enumerate':
                lines.append(f'{n}. {inline(it)}')
            else:
                lines.append(f'- {inline(it)}')
        return '\n'.join(lines)

    def center_block(s):
        # the reviewer-map tabular: convert to a Markdown table
        m = re.search(r'\\begin\{tabular\}\{[^}]*\}(.*?)\\end\{tabular\}', s, re.S)
        if not m:
            return inline(s)
        rows = [r for r in re.split(r'\\\\', m.group(1)) if r.strip() and 'rule' not in r.strip()[:9]]
        rows = [re.sub(r'\\(top|mid|bottom)rule', '', r).strip() for r in rows]
        rows = [r for r in rows if r]
        md = ['| ' + ' | '.join(inline(c) for c in rows[0].split('&')) + ' |', '|' + '---|' * len(rows[0].split('&'))]
        for r in rows[1:]:
            md.append('| ' + ' | '.join(inline(c) for c in r.split('&')) + ' |')
        return '\n'.join(md)

    current_section = ['']
    def heading(level, num, name):
        if level == 2:
            current_section[0] = name
        srcs = SECTION_SOURCES.get(name) or SECTION_SOURCES.get(current_section[0], [])
        cm = f'<!-- section sources: {"; ".join(srcs) if srcs else "none (prose only)"} -->'
        return f'\n{"#" * level} {num + " " if num else ""}{name}\n\n{cm}\n'

    last = 0
    for m in pattern.finditer(text):
        chunk = text[last:m.start()].strip()
        if chunk:
            out.append(inline(chunk) + '\n')
        last = m.end()
        g = m.group(0)
        if g == r'\appendix':
            app = True; sec = [0, 0]; out.append('\n---\n\n# Appendices\n')
        elif g == r'\maketitle' or g.startswith(r'\bibliography') or g == r'\clearpage' or g.startswith(r'\label'):
            if g.startswith(r'\bibliography{'):
                out.append('\n## References\n\n*Rendered from `refs.bib` at build time; citations above are (author, year).*\n')
        elif m.group(1) is not None:
            out.append('\n## Abstract\n\n' + inline(m.group(1)) + '\n')
        elif m.group(2) is not None:
            out.append(heading(2, '', m.group(2)))
        elif m.group(3) is not None:
            sec[0] += 1; sec[1] = 0
            out.append(heading(2, letter(sec[0]) if app else str(sec[0]), inline(m.group(3))))
        elif m.group(4) is not None:
            sec[1] += 1
            out.append(heading(3, f"{letter(sec[0]) if app else sec[0]}.{sec[1]}", inline(m.group(4))))
        elif m.group(5) is not None:
            out.append(table_block(m.group(5)) + '\n')
        elif m.group(6) is not None:
            out.append(figure_block(m.group(6)) + '\n')
        elif m.group(7) is not None:
            eq += 1
            out.append(math_block(m.group(7)) + f'\n\n<!-- equation ({eq}) -->\n')
        elif m.group(8) is not None:
            out.append(list_block(m.group(8), m.group(9)) + '\n')
        elif m.group(10) is not None:
            out.append(center_block(m.group(10)) + '\n')
    chunk = text[last:].strip()
    if chunk:
        out.append(inline(chunk))
    md = '\n'.join(out)
    md = re.sub(r'\n{3,}', '\n\n', md)
    OUT.write_text(md + '\n')
    heads = re.findall(r'^(#{1,3} .*)$', md, re.M)
    print(f'wrote {OUT} ({len(md.splitlines())} lines); headings:')
    for h in heads:
        print('  ' + h)


if __name__ == '__main__':
    main()
