"""Generate the separately sourced oracle and provisional 3D paper supplement.

Normal builds use only hash-verified snapshots inside this worktree. Explicit
--refresh ROOT_COMMIT imports the coordinator's committed selection and reports;
it never selects a model, opens a final cohort, or reads live training output.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import statistics
import subprocess

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = Path('/home/tahmid/Dev/pod-ae-nmrom/Tunable-NM-ROM-Claude')
EVIDENCE = HERE / 'evidence/campaign-2026-09-20'
ORACLE_PIN = 'aa9b55ee7e17f6fa734511f9e4c2481d1715fcdf'
PIN_FILES = {
    'results.json': 'reports/2026-09-20-3d-paper-results.json',
    'selection.json': 'reports/2026-09-20-3d-paper-panel-selection.json',
    'protocol.json': 'reports/2026-09-20-3d-paper-panels/protocol.json',
}


def sha(data):
    return hashlib.sha256(data).hexdigest()


def blob(commit, path):
    return subprocess.check_output(['git', '-C', str(ROOT), 'show', f'{commit}:{path}'])


def refresh(commit):
    commit = subprocess.check_output(['git', '-C', str(ROOT), 'rev-parse', commit]).decode().strip()
    EVIDENCE.mkdir(parents=True, exist_ok=True)
    records = {}
    for name, path in PIN_FILES.items():
        data = blob(commit, path)
        (EVIDENCE / name).write_bytes(data)
        records[name] = dict(repository_path=path, commit=commit, sha256=sha(data))
    for name, path in {
        'oracle.json': 'experiments/p-linear/reports/oracle-confirmation.json',
        'oracle-audit.json': 'experiments/p-linear/artifacts/plorc01/audit.json',
        'oracle-provenance-audit.json': 'experiments/p-linear/artifacts/plorc01/provenance-audit.json',
        'oracle-restore-audit.json': 'experiments/p-linear/artifacts/plorc01/restore-audit.json',
    }.items():
        data = blob(ORACLE_PIN, path)
        (EVIDENCE / name).write_bytes(data)
        records[name] = dict(repository_path=path, commit=ORACLE_PIN, sha256=sha(data))
    selection = json.loads((EVIDENCE / 'selection.json').read_text())
    for panel in selection['panels']:
        name = panel['slug'] + '.pdf'
        path = 'reports/2026-09-20-3d-paper-panels/' + name
        data = blob(commit, path)
        (EVIDENCE / name).write_bytes(data)
        records[name] = dict(repository_path=path, commit=commit, sha256=sha(data))
    (EVIDENCE / 'manifest.json').write_text(json.dumps(dict(
        status='audited development; final 3D cohorts unopened',
        sources=records), indent=2) + '\n')


def tex(value):
    substitutions = {'\\': r'\textbackslash{}', '_': r'\_', '%': r'\%',
                     '&': r'\&', '#': r'\#', '–': '--', '—': '---',
                     '{': r'\{', '}': r'\}'}
    return ''.join(substitutions.get(c, c) for c in str(value))


def pct(value):
    return '---' if value is None else f'{100 * value:.4f}'


def table(name, headers, rows, align=None):
    lines = [r'% Generated by gen_campaign_supplement.py; do not edit.',
             r'\begin{tabular}{' + (align or 'l' + 'r' * (len(headers)-1)) + '}',
             r'\toprule', ' & '.join(headers) + r' \\', r'\midrule']
    lines += [' & '.join(map(str, row)) + r' \\' for row in rows]
    lines += [r'\bottomrule', r'\end{tabular}']
    (HERE / 'tables' / f'{name}.tex').write_text('\n'.join(lines) + '\n')
    md = ['<!-- Generated from hash-pinned campaign evidence. -->',
          '| ' + ' | '.join(headers) + ' |', '| ' + ' | '.join(['---'] * len(headers)) + ' |']
    md += ['| ' + ' | '.join(map(str, row)) + ' |' for row in rows]
    (HERE / 'tables-md' / f'{name}.md').write_text('\n'.join(md) + '\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--refresh', metavar='ROOT_COMMIT')
    args = parser.parse_args()
    if args.refresh:
        refresh(args.refresh)
    manifest = json.loads((EVIDENCE / 'manifest.json').read_text())
    for name, rec in manifest['sources'].items():
        assert sha((EVIDENCE / name).read_bytes()) == rec['sha256'], name
    def read(name):
        return json.loads((EVIDENCE / name).read_text())
    oracle, audit = read('oracle.json'), read('oracle-audit.json')
    assert audit['passed'] and oracle['old_timed_results_unchanged']
    assert read('oracle-provenance-audit.json')['passed']
    assert read('oracle-restore-audit.json')['passed']
    assert read('oracle-restore-audit.json')['result_sha256'] == oracle['result_sha256']
    assert not oracle['global_minimum_proven']
    assert all(row['cases'] == row['stationary'] for row in oracle['rows'])
    assert sha((EVIDENCE / 'oracle-audit.json').read_bytes()) == oracle['audit_sha256']
    macros = {
        'provOracleConfirmationJob': str(oracle['job_id']),
        'provOracleConfirmationSource': oracle['source_commit'][:12],
        'provOracleConfirmationPin': ORACLE_PIN[:12],
        'nOracleConfirmationFits': str(sum(row['cases'] for row in oracle['rows'])),
        'nOracleConfirmationChecks': str(len(audit['checks'])),
    }
    oracle_rows = []
    for row in oracle['rows']:
        assert len(row['per_case']) == row['cases']
        assert abs(max(c['error'] for c in row['per_case']) - row['corrected_worst']) < 1e-14
        assert abs(statistics.median(c['error'] for c in row['per_case']) - row['corrected_median']) < 1e-14
        oracle_rows.append([row['intervals'], row['R'], row['K'], row['q'],
                            'direct' if row['q'] == row['R'] else pct(row['original_starts_worst']),
                            pct(row['corrected_worst']), pct(row['corrected_median']),
                            pct(row['bank_floor_worst']), f"{row['stationary']}/{row['cases']}"])
    table('TC_oracle_confirmation', ['Intervals', '$R$', '$K$', '$q$', 'Original starts',
          'Best found', 'Median', 'Bank floor', 'Stationary'], oracle_rows, 'rrrrrrrrr')
    (HERE / 'tables/campaign-numbers.tex').write_text('\n'.join(
        '\\newcommand{\\' + key + '}{' + value + '}' for key, value in macros.items()) + '\n')
    (HERE / 'tables-md/campaign-numbers.json').write_text(json.dumps(macros, indent=2) + '\n')
    results, selection, protocol = read('results.json'), read('selection.json'), read('protocol.json')
    for name in ('results.json', 'selection.json'):
        source = manifest['sources'][name]
        assert protocol['provenance'][source['repository_path']] == source['sha256']
    runs = {(r['pde'], r['attempt']): r for r in results['runs']}
    sections = []
    selected_count = 0
    provenance_rows = []
    for index, panel in enumerate(selection['panels']):
        run = runs[panel['pde'], panel['attempt']]
        assert run['audit']['passed'], panel
        by_method = {r['method']: r for r in run['rows'] if r['mesh'] == panel['mesh']}
        rows = []
        cases = set()
        for method in panel['methods']:
            row = by_method[method['id']]
            cases.add(row['cases'])
            assert row['cases'] == len(row['per_case'])
            assert row['invocations'] == len(row['gpu_ms_repetitions'])
            assert statistics.median(row['gpu_ms_repetitions']) == row['gpu_ms_median']
            assert sum(t > 1.5 * row['gpu_ms_median'] for t in row['gpu_ms_repetitions']) == row['timing_outliers']
            assert sum(not c['finite'] for c in row['per_case']) == row['nonfinite_cases']
            assert sum(not c['stationary'] for c in row['per_case']) == row['nonstationary_cases']
            assert max(c['evolved'] for c in row['per_case']) == row['evolved_worst']
            assert statistics.median(c['evolved'] for c in row['per_case']) == row['evolved_median']
            rows.append([tex(method['label']), pct(row['evolved_median']), pct(row['evolved_worst']),
                         f"{row['gpu_ms_median']:.3f}", f"{np.quantile(row['gpu_ms_repetitions'], .95):.3f}",
                         f"{row['nonfinite_cases']}/{row['nonstationary_cases']}",
                         f"{row['timing_outliers']}/{row['invocations']}"])
        assert len(cases) == 1
        selected_count += len(rows)
        name = f'TC_development_{index}'
        table(name, ['Method', 'Median (\\%)', 'Worst (\\%)', 'GPU ms', 'p95 ms',
                     'NF/NS', 'Outliers/calls'], rows)
        norm = ('Initial-field-normalized evolved error; same-grid reference.' if run['adapter'] in
                ('burgers', 'ns_trajectory') else
                'Current-reference-normalized evolved error; same-grid reference.')
        if panel['pde'].startswith('Poisson'):
            norm = 'Relative field error against the same-grid discrete solution.'
        sections += [r'\clearpage', r'\subsection{' + tex(panel['pde']) + ': provisional development panel}',
            r'\label{app:campaign:' + str(index) + '}',
            r'\textbf{Provisional:} ' + tex(panel['qualification']) + r'\par',
            r'\begin{table}[h]', r'\centering', r'\small', r'\setlength{\tabcolsep}{3pt}',
            r'\caption{' + tex(panel['mesh_label']) + '; ' + str(next(iter(cases))) +
            ' development cases per method. ' + norm +
            r' Each accuracy/cost pair comes from the same invocation in job ' + tex(run['job_id']) +
            r'. NF/NS counts nonfinite/nonstationary cases; outliers count calls above $1.5$ times the method median.}',
            r'\label{tab:campaign:' + str(index) + '}',
            r'\resizebox{\linewidth}{!}{\input{tables/' + name + '}}', r'\end{table}', r'\FloatBarrier',
            r'\noindent ' + tex(panel['omissions']) + r'\par',
            r'\begin{figure}[h]', r'\centering',
            r'\includegraphics[width=\linewidth]{evidence/campaign-2026-09-20/' + panel['slug'] + '.pdf}',
            r'\caption{Provisional paired development measurements from Table~\ref{tab:campaign:' + str(index) +
            r'}. The right panel isolates the fixed-head correction ladder; the left retains classical controls and operator variants. Zero-error direct solves are identified separately rather than clipped onto the logarithmic error axis.}',
            r'\label{fig:campaign:' + str(index) + '}', r'\end{figure}']
        provenance_rows.append([tex(panel['pde']), tex(panel['attempt']), run['job_id'],
                                tex(run['gpu'].replace('NVIDIA ', '').split(',')[0]),
                                r'\texttt{' + run['source'][:12] + '}'])
        setup = next(s for s in protocol['setups'] if s['pde'] == panel['pde'])
        assert setup['source'] == run['source'] and setup['attempt'] == panel['attempt']
    table('TC_development_sources', ['PDE', 'Attempt', 'Job', 'GPU', 'Scientific source'], provenance_rows, 'lllll')
    setup_rows = [[tex(s['pde']), tex(str(s['training_mesh']) + ' ' + s['mesh_convention'].replace(' per axis', '')),
                   s['training_cases'], s['training_fields_per_case'], s['outputs_per_query'],
                   s['components'], s['bank_rank'], ', '.join(map(str, s['latent_dimensions'])), s['weak_tests']]
                  for s in protocol['setups']]
    table('TC_development_setup', ['PDE', 'Training grid', 'Train cases', 'Fields/case', 'Outputs', 'Channels', '$R$', '$K$', '$M$'], setup_rows, 'llrrrrrrr')
    train_rows = [[tex(o['pde']), tex(o['name'].replace('3d', '')), o['parameters'], o['requested_steps'],
                   o['completed_steps'], o['selected_step'], o['batch_size'], f"{o['initial_learning_rate']:g}",
                   o['training_seed'], tex(o['exit_reason'])] for o in protocol['operators']]
    table('TC_development_training', ['PDE', 'Operator', 'Parameters', 'Budget', 'Done', 'Selected',
                                     'Batch', 'LR', 'Seed', 'Exit'], train_rows, 'llrrrrrrrl')
    nmrom_rows = []
    for record in protocol['nmrom']:
        assert record['completed_steps'] <= record['requested_steps']
        assert record['selected_step'] <= record['completed_steps']
        assert record['network_parameters'] > 0
        assert record['checkpoint'] in protocol['provenance']
        nmrom_rows.append([
            tex(record['pde']), tex(record['role']),
            '$' + r'\!\to\!'.join(map(str, record['mlp_widths'])) + '$',
            record['network_parameters'], record['requested_steps'],
            record['completed_steps'], record['selected_step'], record['model_base_seed'],
        ])
    table('TC_development_nmrom', ['PDE', 'Part', 'MLP widths', 'Parameters',
          'Budget', 'Done', 'Selected', 'Base seed'], nmrom_rows, 'lllrrrrr')
    (HERE / 'sections/campaign-panels-generated.tex').write_text('\n'.join(sections) + '\n')
    check = dict(passed=True, oracle_rows=len(oracle_rows), oracle_fits=int(macros['nOracleConfirmationFits']),
                 independent_oracle_checks=len(audit['checks']), development_rows=selected_count,
                 development_panels=len(selection['panels']), operator_training_records=len(train_rows),
                 nmrom_training_records=len(nmrom_rows),
                 snapshot_manifest_sha256=sha((EVIDENCE / 'manifest.json').read_bytes()),
                 status='development only; final confirmation pending',
                 interpretation='paired measured errors; no cross-job ratios or optimality claim')
    (HERE / 'tables/campaign-provenance.json').write_text(json.dumps(dict(manifest=manifest, audit=check), indent=2) + '\n')
    print(json.dumps(check))


if __name__ == '__main__':
    main()
