"""Two-dimensional operator panel at 256^2: one allocation for the NM-ROM, POD, the operators and the FOM.

Reads only the hash-pinned blobs in evidence/ops-timing-panel-2026-09-22/ (lane ops-timing-panel @ea38c19a,
job 4179247).  Writes tables/TR_ops256.tex (+ .md) and tables/ops-numbers.tex.  No number is typed by hand:
every cell and every macro comes from the summary, and each speedup is re-derived as the row's rule FOM time
divided by the row's own time in the same job.
"""
import hashlib, json
from pathlib import Path

HERE = Path(__file__).resolve().parent
E = HERE / 'evidence/ops-timing-panel-2026-09-22'
MAN = json.loads((E / 'manifest.json').read_text())
for k, v in MAN.items():
    assert hashlib.sha256((E / f'{k}.json').read_bytes()).hexdigest() == v['sha256'], k
S = json.loads((E / 'summary.json').read_text())
A = json.loads((E / 'audit.json').read_text())
assert S['failed_gates'] == [] and S['intervals'] == 256 and not S['suppressed_rows']
assert hashlib.sha256((E / 'audit.json').read_bytes()).hexdigest() == S['audit_sha256']

R = {r['arm']: r for r in S['rows']}
FOM = {a: r for a, r in R.items() if r['family'] == 'fom'}
# the rows the table prints: the two NM-ROM settings of Table 1's family, both POD ranks, every operator arm
SHOW = [('NM-ROM, fast', 'q0_M64_eqcert_g1em06_fastL4'), ('NM-ROM, accurate', 'q256_M1088_eqtop_g0p001'),
        ('POD-LSPG, 256 modes', 'pod256_M1024_dense'), ('POD-LSPG, 512 modes', 'pod512_M2048_dense'),
        ('FNO', 'fno-large'), ('U-Net, small', 'unet-small'), ('U-Net, medium', 'unet-medium'),
        ('U-Net, large', 'unet-large'), ('U-Net, refined', 'unet-refine'), ('Transolver, small', 'tsol-small'),
        ('Transolver, medium', 'tsol-medium'), ('Transolver, large', 'tsol-large'), ('Transolver, refined', 'tsol-refine')]
FAM = {'fno': 'FNO', 'unet': 'U-Net', 'transolver': 'Transolver', 'pod': 'POD-LSPG', 'rom': 'NM-ROM', 'fast': 'NM-ROM', 'fom': 'FOM'}
OPS = [a for a, r in R.items() if r['family'] in ('fno', 'unet', 'transolver')]


def e(x): return f'{x:.2f}' if x >= 0.1 else f'{x:.3f}'
def ms(x): return f'{x:.0f}' if x >= 100 else f'{x:.1f}'
def sp(x): return (f'{x:.2f}' if x < 10 else f'{x:.1f}') + r'$\times$'


def render():
    L = [r'% GENERATED by paper/gen_ops_panel.py from evidence/ops-timing-panel-2026-09-22 -- do not edit.',
         r'\small\setlength{\tabcolsep}{4pt}', r'\begin{tabular}{@{}llrrrlr@{}}', r'\toprule',
         r'Arm & Family & Evolved (\%) & All times (\%) & GPU ms & FOM by the rule & Speedup \\', r'\midrule']
    rows = []
    for label, arm in SHOW:
        r = R[arm]; f = FOM[r['fom_gpu']]
        assert abs(f['median_gpu_ms'] / r['median_gpu_ms'] - r['speedup_gpu']) < 1e-9, arm
        assert f['worst_evolved_percent'] <= r['worst_evolved_percent'] + 1e-12, arm      # the FOM rule, re-derived
        row = [label, FAM[r['family']], e(r['worst_evolved_percent']), e(r['worst_all_times_percent']),
               ms(r['median_gpu_ms']), r'\texttt{' + r['fom_gpu'].replace('_', r'\_') + '}', sp(r['speedup_gpu'])]
        L.append(' & '.join(row) + r' \\'); rows.append(row)
    L.append(r'\midrule')
    for arm in ('nt1e-2_dt01', 'nt1e-3_dt01', 'nt1e-3_dt005'):
        f = FOM[arm]
        row = [r'\texttt{' + arm.replace('_', r'\_') + '}', 'FOM', e(f['worst_evolved_percent']),
               e(f['worst_all_times_percent']), ms(f['median_gpu_ms']), '---', r'1$\times$']
        L.append(' & '.join(row) + r' \\'); rows.append(row)
    L += [r'\bottomrule', r'\end{tabular}']
    return '\n'.join(L) + '\n', rows


def macros():
    fast, acc = R['q0_M64_eqcert_g1em06_fastL4'], R['q256_M1088_eqtop_g0p001']
    _n = {len(r['per_case_evolved_percent']) for r in S['rows']}; assert len(_n) == 1; _cases = _n.pop()
    _r = {o['repetitions_per_case'] for o in S['operators'].values()}; assert len(_r) == 1; _reps = _r.pop()
    op_err = [R[a]['worst_evolved_percent'] for a in OPS]
    faster = [a for a in OPS if R[a]['speedup_gpu'] > 1]
    disc = S['fom_discretisation_error_percent']['dense_tight']
    assert min(op_err) > disc                       # every operator error exceeds the mesh's own discretisation error
    cc = S['fno_error_cross_check'][0]
    assert cc['absolute_difference'] == 0.0 and cc['per_case_max_difference'] == 0.0
    m = dict(nOpsTwoDFastErr=e(fast['worst_evolved_percent']), nOpsTwoDFastMs=ms(fast['median_gpu_ms']),
             nOpsTwoDFastS=f"{fast['speedup_gpu']:.3g}",
             nOpsTwoDAccErr=e(acc['worst_evolved_percent']), nOpsTwoDAccAll=e(acc['worst_all_times_percent']),
             nOpsTwoDAccMs=ms(acc['median_gpu_ms']), nOpsTwoDAccS=f"{acc['speedup_gpu']:.3g}",
             nOpsTwoDOpErrLo=e(min(op_err)), nOpsTwoDOpErrHi=e(max(op_err)),
             nOpsTwoDOpFastS=f"{max(R[a]['speedup_gpu'] for a in OPS):.2f}",
             nOpsTwoDOpFaster=str(len(faster)), nOpsTwoDOpArms=str(len(OPS)),
             nOpsTwoDDisc=f'{disc:.3f}',
             nOpsTwoDPodErrLo=e(min(R[a]['worst_evolved_percent'] for a in ('pod256_M1024_dense', 'pod512_M2048_dense'))),
             nOpsTwoDPodErrHi=e(max(R[a]['worst_evolved_percent'] for a in ('pod256_M1024_dense', 'pod512_M2048_dense'))),
             nOpsTwoDCases=str(_cases), nOpsTwoDReps=str(_reps), nOpsTwoDJob=S['job_id'],
             nOpsTwoDFnoGap=f"{cc['absolute_difference']:.3e}")
    return m




# ---------------------------------------------------------------------------------------------------------------
# DeepONet on 2D Burgers at 256^2 (lane ops-deeponet-b2d @306c939d, job 4179556): accuracy only, no timing claim.
# Same data, split, metric, optimiser, seed and wall budget as the U-Net / Transolver / FNO arms.
ED = HERE / 'evidence/ops-deeponet-b2d-2026-09-22'
MAND = json.loads((ED / 'manifest.json').read_text())
for k, v in MAND.items():
    assert hashlib.sha256((ED / f'{k}.json').read_bytes()).hexdigest() == v['sha256'], k
DS = json.loads((ED / 'summary.json').read_text())
DA = json.loads((ED / 'audit.json').read_text())
assert DA['identical_split_to_fno_job'] and DA['split_hashes_cross_checked_against_archived_manifest']
DROWS = [r for r in DS['rows'] if 'arm' in r and r['cohort'] in ('validation-32', 'diagnosis-8')]
DVAL = {(r['arm'], r['metric']): 100 * r['value'] for r in DROWS if r['cohort'] == 'validation-32'}
DMATCH = {r['arm']: 100 * r['value'] for r in DROWS if r['cohort'] == 'diagnosis-8' and r['metric'] == 'worst_fixed_initial_error'}
DARMS = sorted({r['arm'] for r in DROWS if r['operator'] == 'DeepONet'})
DINFO = {r['arm']: r for r in DROWS}
_pv = DA['persistence_baseline']['validation-32']['fixed_initial']; _pd = DA['persistence_baseline']['diagnosis-8']['fixed_initial']
_D2 = [r for r in DS['rows'] if r.get('metric') == 'D2'][0]
DSHOW = [('DeepONet, small (selected)', 'don-small'), ('DeepONet, medium', 'don-medium'),
         ('DeepONet, refined', 'don-refine'), ('DeepONet, large', 'don-large'),
         ('U-Net, refined', 'unet-refine'), ('Transolver, refined', 'tsol-refine'), ('FNO, large', 'fno-large')]


def deeponet_table():
    L = [r'% GENERATED by paper/gen_ops_panel.py from evidence/ops-deeponet-b2d-2026-09-22 -- do not edit.',
         r'\small', r'\begin{tabular}{@{}llrrrr@{}}', r'\toprule',
         r' & & \multicolumn{3}{c}{Validation, 32 cases} & Matched 8 \\',
         r'\cmidrule(lr){3-5}\cmidrule(l){6-6}',
         r'Arm & Ended by & Mean (\%) & Median (\%) & Worst (\%) & Worst (\%) \\', r'\midrule']
    rows = []
    for label, arm in DSHOW:
        r = DINFO[arm]
        row = [label, r['stop_reason'].replace('_', ' '), e(DVAL[(arm, 'mean_fixed_initial_error')]),
               e(DVAL[(arm, 'median_fixed_initial_error')]), e(DVAL[(arm, 'worst_fixed_initial_error')]), e(DMATCH[arm])]
        L.append(' & '.join(row) + r' \\'); rows.append(row)
    L.append(r'\midrule')
    for row in ([r'NM-ROM (same cohort)', '---', '---', '---', '---', e(100 * _D2['rom'])],
                [r'Persistence control', '---', e(100 * _pv['mean']), e(100 * _pv['median']),
                 e(100 * _pv['maximum']), e(100 * _pd['maximum'])]):
        L.append(' & '.join(row) + r' \\'); rows.append(row)
    L += [r'\bottomrule', r'\end{tabular}']
    return '\n'.join(L) + '\n', rows


def deeponet_macros():
    dm = [DVAL[(a, 'mean_fixed_initial_error')] for a in DARMS]
    others = [DVAL[(a, 'mean_fixed_initial_error')] for a in ('unet-refine', 'tsol-refine', 'fno-large')]
    tr = [100 * DA['arms'][a]['train_loss_at_best'] ** 0.5 for a in DARMS]
    cases = {DA['arms'][a]['training_cases'] for a in DARMS}; assert len(cases) == 1
    stop = {DA['arms'][a]['stop_reason'] for a in DARMS}; assert stop == {'early_stopping'}       # none ran out of budget
    assert all(DA['arms'][a]['train_loss_final'] < DA['arms'][a]['train_loss_at_best'] for a in DARMS)  # training loss still falling
    assert min(dm) > max(others) and min(dm) < 100 * _pv['mean']              # worse than the other families, better than persistence
    # where the panel's discretisation-error comparison does and does not hold (ops-tune-grid correction, 2026-09-22)
    bar = S['fom_discretisation_error_percent']['dense_tight']
    pub = sorted({a for a, _ in DVAL if not a.startswith('don-')})
    below_val = [a for a in pub if DVAL[(a, 'worst_fixed_initial_error')] < bar]
    below_match = [a for a in pub if DMATCH[a] < bar]
    assert len(below_val) >= 1 and len(below_match) == len(pub)          # the bar is not exceeded everywhere off the panel's cohort
    _u = 'unet-refine'
    same_panel = R[_u]['worst_evolved_percent']; same_match = DMATCH[_u]
    return dict(nOpsBarSamePanel=e(same_panel), nOpsBarSameMatch=e(same_match),
                nOpsBarSameGap=f'{same_panel / same_match:.1f}',
                nOpsBarPubArms=str(len(pub)), nOpsBarBelowVal=str(len(below_val)),
                nOpsBarBelowValName=below_val[0].replace('-', '\\mbox{-}') if len(below_val) == 1 else '',
                nOpsBarBelowValErr=e(min(DVAL[(a, 'worst_fixed_initial_error')] for a in below_val)),
                nOpsBarBelowMatch=str(len(below_match)),
                nDonArms=str(len(DARMS)), nDonMeanLo=e(min(dm)), nDonMeanHi=e(max(dm)),
                nDonSelWorst=e(DVAL[('don-small', 'worst_fixed_initial_error')]),
                nDonMatchLo=e(min(DMATCH[a] for a in DARMS)), nDonMatchHi=e(max(DMATCH[a] for a in DARMS)),
                nDonOtherMeanLo=e(min(others)), nDonOtherMeanHi=e(max(others)),
                nDonRomMatch=e(100 * _D2['rom']), nDonPersistMean=e(100 * _pv['mean']),
                nDonVsPersist=f"{100 * _pv['mean'] / min(dm):.1f}", nDonTrainCases=str(cases.pop()),
                nDonTrainRmsLo=e(min(tr)), nDonTrainRmsHi=e(max(tr)),
                nDonPatience=str({DA['arms'][a]['config']['patience'] for a in DARMS}.pop()),
                nDonEpochCap=str({DA['arms'][a]['config']['epochs'] for a in DARMS}.pop()),
                nDonJob=DA['job_id'])




# ---------------------------------------------------------------------------------------------------------------
# Data-parity accounting (lane ops-tune-grid @4fee6965).  Primitive counts and the measured per-trajectory cost are
# read from the pinned arithmetic re-derivation; every ratio below is recomputed here rather than quoted.
EP = HERE / 'evidence/ops-data-parity-2026-09-22'
MANP = json.loads((EP / 'manifest.json').read_text())
for k, v in MANP.items():
    assert hashlib.sha256((EP / k).read_bytes()).hexdigest() == v['sha256'], k
PAR = (EP / 'for-paper-arithmetic.txt').read_text()
import re as _re


def _num(pat):
    m = _re.search(pat, PAR); assert m, pat
    return float(m.group(1))


def parity_macros():
    op_s = _num(r'operator s/trajectory: median ([0-9.]+)')
    op_traj = int(_num(r'(\d+) cases at pinned fidelity'))
    rom_traj = int(_num(r'(\d+) cases at pinned fidelity: 586135'))
    per_traj = int(_num(r'states available \d+\*(\d+) ='))
    per_case = int(_num(r'operator supervised states \d+\*(\d+) ='))
    rom_states = int(_num(r'state ratio (\d+)/'))
    ratio = _num(r'cost ratio ([0-9.]+)')                       # 127.2 s vs the NM-ROM's 0.19 s (job 2837431's log)
    rom_s = op_s / ratio
    fmt = lambda n: f'{n:,}'.replace(',', r'\,')
    return dict(nParOpTraj=str(op_traj), nParRomTraj=fmt(rom_traj),
                nParTrajRatio=f'{rom_traj / op_traj:.0f}',
                nParOpSec=f'{op_s:.1f}', nParRomSec=f'{rom_s:.2f}', nParCostRatio=f'{round(ratio, -1):.0f}',
                nParOpHours=f'{op_traj * op_s / 3600:.1f}', nParFullHours=f'{rom_traj * op_s / 3600:.0f}',
                nParOpStates=fmt(op_traj * per_case), nParPerCase=str(per_case),
                nParRomStates=fmt(rom_states), nParStatesAvail=fmt(rom_traj * per_traj),
                nParRomJob='2837431')


if __name__ == '__main__':
    tex, rows = render()
    (HERE / 'tables/TR_ops256.tex').write_text(tex)
    head = ['Arm', 'Family', 'Evolved (%)', 'All times (%)', 'GPU ms', 'FOM by the rule', 'Speedup']
    clean = lambda s: s.replace(r'\texttt{', '').replace('}', '').replace(r'\_', '_').replace(r'$\times$', '×')
    (HERE / 'tables-md/TR_ops256.md').write_text('| ' + ' | '.join(head) + ' |\n| ' + ' | '.join(['---'] * len(head)) + ' |\n'
                                                 + ''.join('| ' + ' | '.join(clean(c) for c in r) + ' |\n' for r in rows))
    dtex, drows = deeponet_table()
    (HERE / 'tables/TR_deeponet2d.tex').write_text(dtex)
    dhead = ['Arm', 'Ended by', 'Val. mean (%)', 'Val. median (%)', 'Val. worst (%)', 'Matched-8 worst (%)']
    (HERE / 'tables-md/TR_deeponet2d.md').write_text('| ' + ' | '.join(dhead) + ' |\n| ' + ' | '.join(['---'] * len(dhead)) + ' |\n'
                                                     + ''.join('| ' + ' | '.join(r) + ' |\n' for r in drows))
    m = macros(); m.update(deeponet_macros()); m.update(parity_macros())
    (HERE / 'tables/ops-numbers.tex').write_text('% GENERATED by paper/gen_ops_panel.py -- do not edit.\n'
                                                 + ''.join(f'\\newcommand{{\\{k}}}{{{v}}}\n' for k, v in sorted(m.items())))
    print('deeponet panel:', len(drows), 'rows')
    print('ops panel:', len(rows), 'rows;', m['nOpsTwoDOpFaster'], 'of', m['nOpsTwoDOpArms'], 'operator arms beat their FOM')
