"""Table: correction-rank tunability at 4096^2 (replaces the former Figure 2, fig_tunability_rank).

Reads ONLY paper/tables/headline-provenance.json ("tunability", written by gen_headline.py from hash-pinned
snapshots) -- the same data the figure generator reads.  One frozen model and one allocation per series; every
speedup is that series' ONE full-order setting's median GPU ms divided by the rung's, re-derived here and asserted
against the stored ratio.  Writes tables/TH_tunability.tex (+ tables-md/TH_tunability.md).

Layout: development-cohort columns and held-out-cohort columns side by side, so the two Burgers series (same
settings, same allocation type, different cohorts) share rows; heat (sealed held-out cohort) fills the held-out
columns and Poisson (development sources) the development columns.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROV = json.loads((HERE / 'tables/headline-provenance.json').read_text())

BLOCKS = [  # (block label, development series, held-out series)
    ('Burgers 2D (6 development / 64 held-out cases)', 'Burgers 2D, development (6)', 'Burgers 2D, held-out (64)'),
    ('Heat 2D, wide bank (16 sealed held-out cases)', None, 'Heat 2D (wide bank), sealed (16)'),
    ('Poisson 2D (12 development sources)', 'Poisson 2D, development (12)', None),
]


def e(x): return f'{x:.2f}' if x >= 0.1 else f'{x:.3f}'
def ms(x): return f'{x:.0f}' if round(x, 1) >= 100 else f'{x:.1f}'
def sp(x): return (f'{x:.0f}' if x >= 100 else f'{x:.1f}' if x >= 10 else f'{x:.2f}') + r'$\times$'


def fom_label(arm):
    def tol(x):
        m_, ex = f'{float(x):.0e}'.split('e'); ex = int(ex)
        return f'10^{{{ex}}}' if m_ == '1' else f'{m_}{{\\times}}10^{{{ex}}}'
    if arm.startswith('lean_nt'): return 'tol.\\ $' + tol(arm.split('_nt')[1].split('_')[0]) + '$'
    if arm.startswith('fom_cncg'): return '$\\Delta t=' + arm.split('_dt')[1].split('_')[0] + '$, rtol $' + tol(arm.split('rtol')[1].split('_')[0]) + '$'
    return 'rtol $' + tol(arm.split('_')[1]) + '$'


def setting(r, fam):
    s = f"$q={r['q']}$" + (f", $M={r['M']}$" if fam == 'Burgers' else '')
    if r['kind'] == 'tolerance': s += r', looser tol.$^{\star}$'
    if not r['certified']: s += r'$^{\dagger}$'
    return s


def key(r): return (r['q'], r.get('M') or 0, r['kind'])


def cells(r, fom):
    if r is None: return ['---'] * 3
    assert abs(fom['ms'] / r['ms'] - r['speedup']) < 1e-9          # ratio re-derived from the same record
    return [e(r['err']), ms(r['ms']), sp(fom['ms'] / r['ms'])]


def render():
    ser = {s['series']: s for s in PROV['tunability']}
    assert set(ser) == {x for b in BLOCKS for x in b[1:] if x}, set(ser)
    L = [r'% GENERATED by paper/gen_tunability_table.py from tables/headline-provenance.json -- do not edit.',
         r'\small\setlength{\tabcolsep}{4pt}', r'\begin{tabular}{@{}lrrrrrr@{}}', r'\toprule',
         r' & \multicolumn{3}{c}{Development cohort} & \multicolumn{3}{c}{Held-out cohort} \\',
         r'\cmidrule(lr){2-4}\cmidrule(l){5-7}',
         r'Setting & Err.\ (\%) & ms & Speedup & Err.\ (\%) & ms & Speedup \\']
    rows_md = []
    for lab, dev, held in BLOCKS:
        L += [r'\midrule', r'\multicolumn{7}{@{}l}{\emph{' + lab + r'}} \\']
        rows_md.append([lab] + [''] * 6)
        D, H = ser.get(dev), ser.get(held)
        fam = lab.split()[0]
        ref = D or H
        names = {x['fom']['name'] for x in (D, H) if x}; arms = {x['fom']['arm'] for x in (D, H) if x}
        assert len(names) == 1 and len(arms) == 1                     # one named FOM setting per block
        keys = sorted({key(r) for x in (D, H) if x for r in x['rungs']})
        byk = lambda x: {key(r): r for r in x['rungs']} if x else {}
        dk, hk = byk(D), byk(H)
        first = True
        for k in keys:
            r0 = dk.get(k) or hk.get(k)
            if dk.get(k) and hk.get(k): assert dk[k]['certified'] == hk[k]['certified'] and dk[k]['kind'] == hk[k]['kind']
            c = cells(dk.get(k), D['fom'] if D else None) + cells(hk.get(k), H['fom'] if H else None)
            row = [setting(r0, fam)] + c
            L.append(' & '.join(row) + r' \\'); rows_md.append(row); first = False
        fl = [f"{ref['fom']['name']}, {fom_label(ref['fom']['arm'])}"]
        fc = [(e(x['fom']['err']), ms(x['fom']['ms']), r'1$\times$') if x else ('---',) * 3 for x in (D, H)]
        row = [r'\emph{FOM:} ' + fl[0]] + list(fc[0]) + list(fc[1])
        L.append(' & '.join(row) + r' \\'); rows_md.append(row)
    L += [r'\bottomrule', r'\end{tabular}']
    return '\n'.join(L) + '\n', rows_md


if __name__ == '__main__':
    tex, rows = render()
    (HERE / 'tables/TH_tunability.tex').write_text(tex)
    head = ['Setting', 'Dev. err (%)', 'Dev. ms', 'Dev. speedup', 'Held-out err (%)', 'Held-out ms', 'Held-out speedup']
    clean = lambda s: s.replace('$', '').replace(r'\times', '×').replace(r'{\times}', '×').replace(r'\emph{', '').replace('}', '').replace('{', '').replace(r'\ ', ' ').replace('--', '–').replace('^', '')
    (HERE / 'tables-md/TH_tunability.md').write_text('| ' + ' | '.join(head) + ' |\n| ' + ' | '.join(['---'] * len(head)) + ' |\n'
                                                   + ''.join('| ' + ' | '.join(clean(c) for c in r) + ' |\n' for r in rows))
    print('tunability table:', len(rows), 'rows')
