"""Two-dimensional operator panel at 256^2: one allocation for the NM-ROM, POD, the operators and the FOM.

Reads only the hash-pinned blobs in evidence/ops-timing-panel-2026-09-22/ (lane ops-timing-panel @ea38c19a,
job 4179247).  Writes tables/TR_ops256.tex (+ .md) and tables/ops-numbers.tex.  No number is typed by hand:
every cell and every macro comes from the summary, and each speedup is re-derived as the row's rule FOM time
divided by the row's own time in the same job.
"""
import hashlib, json
from pathlib import Path

HERE = Path(__file__).resolve().parent
E = HERE / 'evidence/ops-timing-panel-2026-09-22'
MAN = json.loads((E / 'manifest.json').read_text())
for k, v in MAN.items():
    assert hashlib.sha256((E / f'{k}.json').read_bytes()).hexdigest() == v['sha256'], k
S = json.loads((E / 'summary.json').read_text())
A = json.loads((E / 'audit.json').read_text())
assert S['failed_gates'] == [] and S['intervals'] == 256 and not S['suppressed_rows']
assert hashlib.sha256((E / 'audit.json').read_bytes()).hexdigest() == S['audit_sha256']

R = {r['arm']: r for r in S['rows']}
FOM = {a: r for a, r in R.items() if r['family'] == 'fom'}
# the rows the table prints: the two NM-ROM settings of Table 1's family, both POD ranks, every operator arm
SHOW = [('NM-ROM, fast', 'q0_M64_eqcert_g1em06_fastL4'), ('NM-ROM, accurate', 'q256_M1088_eqtop_g0p001'),
        ('POD-LSPG, 256 modes', 'pod256_M1024_dense'), ('POD-LSPG, 512 modes', 'pod512_M2048_dense'),
        ('FNO', 'fno-large'), ('U-Net, small', 'unet-small'), ('U-Net, medium', 'unet-medium'),
        ('U-Net, large', 'unet-large'), ('U-Net, refined', 'unet-refine'), ('Transolver, small', 'tsol-small'),
        ('Transolver, medium', 'tsol-medium'), ('Transolver, large', 'tsol-large'), ('Transolver, refined', 'tsol-refine')]
FAM = {'fno': 'FNO', 'unet': 'U-Net', 'transolver': 'Transolver', 'pod': 'POD-LSPG', 'rom': 'NM-ROM', 'fast': 'NM-ROM', 'fom': 'FOM'}
OPS = [a for a, r in R.items() if r['family'] in ('fno', 'unet', 'transolver')]


def e(x): return f'{x:.2f}' if x >= 0.1 else f'{x:.3f}'
def ms(x): return f'{x:.0f}' if x >= 100 else f'{x:.1f}'
def sp(x): return (f'{x:.2f}' if x < 10 else f'{x:.1f}') + r'$\times$'


def render():
    L = [r'% GENERATED by paper/gen_ops_panel.py from evidence/ops-timing-panel-2026-09-22 -- do not edit.',
         r'\small\setlength{\tabcolsep}{4pt}', r'\begin{tabular}{@{}llrrrlr@{}}', r'\toprule',
         r'Arm & Family & Evolved (\%) & All times (\%) & GPU ms & FOM by the rule & Speedup \\', r'\midrule']
    rows = []
    for label, arm in SHOW:
        r = R[arm]; f = FOM[r['fom_gpu']]
        assert abs(f['median_gpu_ms'] / r['median_gpu_ms'] - r['speedup_gpu']) < 1e-9, arm
        assert f['worst_evolved_percent'] <= r['worst_evolved_percent'] + 1e-12, arm      # the FOM rule, re-derived
        row = [label, FAM[r['family']], e(r['worst_evolved_percent']), e(r['worst_all_times_percent']),
               ms(r['median_gpu_ms']), r'\texttt{' + r['fom_gpu'].replace('_', r'\_') + '}', sp(r['speedup_gpu'])]
        L.append(' & '.join(row) + r' \\'); rows.append(row)
    L.append(r'\midrule')
    for arm in ('nt1e-2_dt01', 'nt1e-3_dt01', 'nt1e-3_dt005'):
        f = FOM[arm]
        row = [r'\texttt{' + arm.replace('_', r'\_') + '}', 'FOM', e(f['worst_evolved_percent']),
               e(f['worst_all_times_percent']), ms(f['median_gpu_ms']), '---', r'1$\times$']
        L.append(' & '.join(row) + r' \\'); rows.append(row)
    L += [r'\bottomrule', r'\end{tabular}']
    return '\n'.join(L) + '\n', rows


def macros():
    fast, acc = R['q0_M64_eqcert_g1em06_fastL4'], R['q256_M1088_eqtop_g0p001']
    _n = {len(r['per_case_evolved_percent']) for r in S['rows']}; assert len(_n) == 1; _cases = _n.pop()
    _r = {o['repetitions_per_case'] for o in S['operators'].values()}; assert len(_r) == 1; _reps = _r.pop()
    op_err = [R[a]['worst_evolved_percent'] for a in OPS]
    faster = [a for a in OPS if R[a]['speedup_gpu'] > 1]
    disc = S['fom_discretisation_error_percent']['dense_tight']
    assert min(op_err) > disc                       # every operator error exceeds the mesh's own discretisation error
    cc = S['fno_error_cross_check'][0]
    assert cc['absolute_difference'] == 0.0 and cc['per_case_max_difference'] == 0.0
    m = dict(nOpsTwoDFastErr=e(fast['worst_evolved_percent']), nOpsTwoDFastMs=ms(fast['median_gpu_ms']),
             nOpsTwoDFastS=f"{fast['speedup_gpu']:.3g}",
             nOpsTwoDAccErr=e(acc['worst_evolved_percent']), nOpsTwoDAccAll=e(acc['worst_all_times_percent']),
             nOpsTwoDAccMs=ms(acc['median_gpu_ms']), nOpsTwoDAccS=f"{acc['speedup_gpu']:.3g}",
             nOpsTwoDOpErrLo=e(min(op_err)), nOpsTwoDOpErrHi=e(max(op_err)),
             nOpsTwoDOpFastS=f"{max(R[a]['speedup_gpu'] for a in OPS):.2f}",
             nOpsTwoDOpFaster=str(len(faster)), nOpsTwoDOpArms=str(len(OPS)),
             nOpsTwoDDisc=f'{disc:.3f}',
             nOpsTwoDPodErrLo=e(min(R[a]['worst_evolved_percent'] for a in ('pod256_M1024_dense', 'pod512_M2048_dense'))),
             nOpsTwoDPodErrHi=e(max(R[a]['worst_evolved_percent'] for a in ('pod256_M1024_dense', 'pod512_M2048_dense'))),
             nOpsTwoDCases=str(_cases), nOpsTwoDReps=str(_reps), nOpsTwoDJob=S['job_id'],
             nOpsTwoDFnoGap=f"{cc['absolute_difference']:.3e}")
    return m


if __name__ == '__main__':
    tex, rows = render()
    (HERE / 'tables/TR_ops256.tex').write_text(tex)
    head = ['Arm', 'Family', 'Evolved (%)', 'All times (%)', 'GPU ms', 'FOM by the rule', 'Speedup']
    clean = lambda s: s.replace(r'\texttt{', '').replace('}', '').replace(r'\_', '_').replace(r'$\times$', '×')
    (HERE / 'tables-md/TR_ops256.md').write_text('| ' + ' | '.join(head) + ' |\n| ' + ' | '.join(['---'] * len(head)) + ' |\n'
                                                 + ''.join('| ' + ' | '.join(clean(c) for c in r) + ' |\n' for r in rows))
    m = macros()
    (HERE / 'tables/ops-numbers.tex').write_text('% GENERATED by paper/gen_ops_panel.py -- do not edit.\n'
                                                 + ''.join(f'\\newcommand{{\\{k}}}{{{v}}}\n' for k, v in sorted(m.items())))
    print('ops panel:', len(rows), 'rows;', m['nOpsTwoDOpFaster'], 'of', m['nOpsTwoDOpArms'], 'operator arms beat their FOM')
